package model.duplicateparkingspace.services.client;

import model.duplicateparkingspace.services.common.DuplicateParkingSpaceAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 24 17:04:06 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DuplicateParkingSpaceAMClient extends ApplicationModuleImpl implements DuplicateParkingSpaceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public DuplicateParkingSpaceAMClient() {
    }

    public void logProcedure() {
        Object _ret = this.riInvokeExportedMethod(this,"logProcedure",null,null);
        return;
    }

    public String CallDuplicateParkingSpace(Number parkingSpaceId, String postId,
                                            Number spaceNumber, String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CallDuplicateParkingSpace",new String [] {"java.lang.Number","java.lang.String","java.lang.Number","java.lang.String"},new Object[] {parkingSpaceId, postId, spaceNumber, userId});
        return (String)_ret;
    }
}
