package model.bulkeditgroups.views.client;

import model.bulkeditgroups.views.common.GroupHeaderUpdtVO;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 27 18:52:48 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupHeaderUpdtVOClient extends ViewUsageImpl implements GroupHeaderUpdtVO {
    /**
     * This is the default constructor (do not remove).
     */
    public GroupHeaderUpdtVOClient() {
    }

    public void setCreateDateRangeEnd(Date value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setCreateDateRangeEnd",new String [] {"oracle.jbo.domain.Date"},new Object[] {value});
        return;
    }

    public void setCreateDateRangeStart(Date value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setCreateDateRangeStart",new String [] {"oracle.jbo.domain.Date"},new Object[] {value});
        return;
    }
}
