package model.duplicateparkingspace.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 24 17:04:06 PST 2012
// ---------------------------------------------------------------------
public interface DuplicateParkingSpaceAM extends ApplicationModule {
    void logProcedure();

    String CallDuplicateParkingSpace(Number parkingSpaceId, String postId, Number spaceNumber,
                                     String userId);
}
