package model.bulkeditgroups.views.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 27 18:52:48 PDT 2012
// ---------------------------------------------------------------------
public interface GroupHeaderUpdtVO extends ViewObject {
    void setCreateDateRangeEnd(Date value);

    void setCreateDateRangeStart(Date value);
}
