package model.availableapioverrides.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:43:16 PST 2012
// ---------------------------------------------------------------------
public interface AvailApiBlocksVwRoVORow extends Row {
    Number getBlockId();

    void setBlockId(Number value);

    Boolean getSelectedBlock();

    void setSelectedBlock(Boolean value);
}
