package model.availableapioverrides.views;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:07:11 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AAOJoinedUpdtVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        AAOLastUpdUser {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getAAOLastUpdUser();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setAAOLastUpdUser((String)value);
            }
        }
        ,
        AAOCreatedDt {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getAAOCreatedDt();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setAAOCreatedDt((Date)value);
            }
        }
        ,
        AAOLastUpdDt {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getAAOLastUpdDt();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setAAOLastUpdDt((Date)value);
            }
        }
        ,
        AAOLastUpdPgm {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getAAOLastUpdPgm();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setAAOLastUpdPgm((String)value);
            }
        }
        ,
        PmDistrictId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getPmDistrictId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setPmDistrictId((Number)value);
            }
        }
        ,
        PmDistrictSdeId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getPmDistrictSdeId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setPmDistrictSdeId((Number)value);
            }
        }
        ,
        PmDistrictName {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getPmDistrictName();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setPmDistrictName((String)value);
            }
        }
        ,
        OspId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getOspId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setOspId((Number)value);
            }
        }
        ,
        OspInvFacilityName {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getOspInvFacilityName();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setOspInvFacilityName((String)value);
            }
        }
        ,
        BlockId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlockId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlockId((Number)value);
            }
        }
        ,
        BlocksSdeId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlocksSdeId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlocksSdeId((Number)value);
            }
        }
        ,
        BlocksBlockNum {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlocksBlockNum();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlocksBlockNum((Number)value);
            }
        }
        ,
        BlocksStreetName {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlocksStreetName();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlocksStreetName((String)value);
            }
        }
        ,
        BlockfaceId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlockfaceId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlockfaceId((Number)value);
            }
        }
        ,
        BlockfaceSdeId {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlockfaceSdeId();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlockfaceSdeId((Number)value);
            }
        }
        ,
        BlockfaceStreetName {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlockfaceStreetName();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlockfaceStreetName((String)value);
            }
        }
        ,
        BlockfaceBlockNum {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlockfaceBlockNum();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlockfaceBlockNum((Number)value);
            }
        }
        ,
        BlockfaceStrNumParity {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getBlockfaceStrNumParity();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setBlockfaceStrNumParity((String)value);
            }
        }
        ,
        Description {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        SelectedForDeletion {
            public Object get(AAOJoinedUpdtVORowImpl obj) {
                return obj.getSelectedForDeletion();
            }

            public void put(AAOJoinedUpdtVORowImpl obj, Object value) {
                obj.setSelectedForDeletion((Boolean)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(AAOJoinedUpdtVORowImpl object);

        public abstract void put(AAOJoinedUpdtVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int AAOLASTUPDUSER = AttributesEnum.AAOLastUpdUser.index();
    public static final int AAOCREATEDDT = AttributesEnum.AAOCreatedDt.index();
    public static final int AAOLASTUPDDT = AttributesEnum.AAOLastUpdDt.index();
    public static final int AAOLASTUPDPGM = AttributesEnum.AAOLastUpdPgm.index();
    public static final int PMDISTRICTID = AttributesEnum.PmDistrictId.index();
    public static final int PMDISTRICTSDEID = AttributesEnum.PmDistrictSdeId.index();
    public static final int PMDISTRICTNAME = AttributesEnum.PmDistrictName.index();
    public static final int OSPID = AttributesEnum.OspId.index();
    public static final int OSPINVFACILITYNAME = AttributesEnum.OspInvFacilityName.index();
    public static final int BLOCKID = AttributesEnum.BlockId.index();
    public static final int BLOCKSSDEID = AttributesEnum.BlocksSdeId.index();
    public static final int BLOCKSBLOCKNUM = AttributesEnum.BlocksBlockNum.index();
    public static final int BLOCKSSTREETNAME = AttributesEnum.BlocksStreetName.index();
    public static final int BLOCKFACEID = AttributesEnum.BlockfaceId.index();
    public static final int BLOCKFACESDEID = AttributesEnum.BlockfaceSdeId.index();
    public static final int BLOCKFACESTREETNAME = AttributesEnum.BlockfaceStreetName.index();
    public static final int BLOCKFACEBLOCKNUM = AttributesEnum.BlockfaceBlockNum.index();
    public static final int BLOCKFACESTRNUMPARITY = AttributesEnum.BlockfaceStrNumParity.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SELECTEDFORDELETION = AttributesEnum.SelectedForDeletion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AAOJoinedUpdtVORowImpl() {
    }

    /**
     * Gets AvailApiOverridesEO entity object.
     * @return the AvailApiOverridesEO
     */
    public EntityImpl getAvailApiOverridesEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets PmDistrictsEO entity object.
     * @return the PmDistrictsEO
     */
    public EntityImpl getPmDistrictsEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets OspInventoryEO entity object.
     * @return the OspInventoryEO
     */
    public EntityImpl getOspInventoryEO() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets BlocksEO entity object.
     * @return the BlocksEO
     */
    public EntityImpl getBlocksEO() {
        return (EntityImpl)getEntity(3);
    }

    /**
     * Gets BlockfacesEO entity object.
     * @return the BlockfacesEO
     */
    public EntityImpl getBlockfacesEO() {
        return (EntityImpl)getEntity(4);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_USER using the alias name AAOLastUpdUser.
     * @return the LAST_UPD_USER
     */
    public String getAAOLastUpdUser() {
        return (String) getAttributeInternal(AAOLASTUPDUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_USER using the alias name AAOLastUpdUser.
     * @param value value to set the LAST_UPD_USER
     */
    public void setAAOLastUpdUser(String value) {
        setAttributeInternal(AAOLASTUPDUSER, value);
    }

    /**
     * Gets the attribute value for CREATED_DT using the alias name AAOCreatedDt.
     * @return the CREATED_DT
     */
    public Date getAAOCreatedDt() {
        return (Date) getAttributeInternal(AAOCREATEDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DT using the alias name AAOCreatedDt.
     * @param value value to set the CREATED_DT
     */
    public void setAAOCreatedDt(Date value) {
        setAttributeInternal(AAOCREATEDDT, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_DT using the alias name AAOLastUpdDt.
     * @return the LAST_UPD_DT
     */
    public Date getAAOLastUpdDt() {
        return (Date) getAttributeInternal(AAOLASTUPDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_DT using the alias name AAOLastUpdDt.
     * @param value value to set the LAST_UPD_DT
     */
    public void setAAOLastUpdDt(Date value) {
        setAttributeInternal(AAOLASTUPDDT, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_PGM using the alias name AAOLastUpdPgm.
     * @return the LAST_UPD_PGM
     */
    public String getAAOLastUpdPgm() {
        return (String) getAttributeInternal(AAOLASTUPDPGM);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_PGM using the alias name AAOLastUpdPgm.
     * @param value value to set the LAST_UPD_PGM
     */
    public void setAAOLastUpdPgm(String value) {
        setAttributeInternal(AAOLASTUPDPGM, value);
    }

    /**
     * Gets the attribute value for PM_DISTRICT_ID using the alias name PmDistrictId.
     * @return the PM_DISTRICT_ID
     */
    public Number getPmDistrictId() {
        return (Number) getAttributeInternal(PMDISTRICTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PM_DISTRICT_ID using the alias name PmDistrictId.
     * @param value value to set the PM_DISTRICT_ID
     */
    public void setPmDistrictId(Number value) {
        setAttributeInternal(PMDISTRICTID, value);
    }

    /**
     * Gets the attribute value for SDE_ID using the alias name PmDistrictSdeId.
     * @return the SDE_ID
     */
    public Number getPmDistrictSdeId() {
        return (Number) getAttributeInternal(PMDISTRICTSDEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SDE_ID using the alias name PmDistrictSdeId.
     * @param value value to set the SDE_ID
     */
    public void setPmDistrictSdeId(Number value) {
        setAttributeInternal(PMDISTRICTSDEID, value);
    }

    /**
     * Gets the attribute value for PM_DISTRICT_NAME using the alias name PmDistrictName.
     * @return the PM_DISTRICT_NAME
     */
    public String getPmDistrictName() {
        return (String) getAttributeInternal(PMDISTRICTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PM_DISTRICT_NAME using the alias name PmDistrictName.
     * @param value value to set the PM_DISTRICT_NAME
     */
    public void setPmDistrictName(String value) {
        setAttributeInternal(PMDISTRICTNAME, value);
    }

    /**
     * Gets the attribute value for OSP_ID using the alias name OspId.
     * @return the OSP_ID
     */
    public Number getOspId() {
        return (Number) getAttributeInternal(OSPID);
    }

    /**
     * Sets <code>value</code> as attribute value for OSP_ID using the alias name OspId.
     * @param value value to set the OSP_ID
     */
    public void setOspId(Number value) {
        setAttributeInternal(OSPID, value);
    }

    /**
     * Gets the attribute value for FACILITY_NAME using the alias name OspInvFacilityName.
     * @return the FACILITY_NAME
     */
    public String getOspInvFacilityName() {
        return (String) getAttributeInternal(OSPINVFACILITYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FACILITY_NAME using the alias name OspInvFacilityName.
     * @param value value to set the FACILITY_NAME
     */
    public void setOspInvFacilityName(String value) {
        setAttributeInternal(OSPINVFACILITYNAME, value);
    }

    /**
     * Gets the attribute value for BLOCK_ID using the alias name BlockId.
     * @return the BLOCK_ID
     */
    public Number getBlockId() {
        return (Number) getAttributeInternal(BLOCKID);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOCK_ID using the alias name BlockId.
     * @param value value to set the BLOCK_ID
     */
    public void setBlockId(Number value) {
        setAttributeInternal(BLOCKID, value);
    }

    /**
     * Gets the attribute value for SDE_ID using the alias name BlocksSdeId.
     * @return the SDE_ID
     */
    public Number getBlocksSdeId() {
        return (Number) getAttributeInternal(BLOCKSSDEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SDE_ID using the alias name BlocksSdeId.
     * @param value value to set the SDE_ID
     */
    public void setBlocksSdeId(Number value) {
        setAttributeInternal(BLOCKSSDEID, value);
    }

    /**
     * Gets the attribute value for BLOCK_NUM using the alias name BlocksBlockNum.
     * @return the BLOCK_NUM
     */
    public Number getBlocksBlockNum() {
        return (Number) getAttributeInternal(BLOCKSBLOCKNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOCK_NUM using the alias name BlocksBlockNum.
     * @param value value to set the BLOCK_NUM
     */
    public void setBlocksBlockNum(Number value) {
        setAttributeInternal(BLOCKSBLOCKNUM, value);
    }

    /**
     * Gets the attribute value for STREET_NAME using the alias name BlocksStreetName.
     * @return the STREET_NAME
     */
    public String getBlocksStreetName() {
        return (String) getAttributeInternal(BLOCKSSTREETNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for STREET_NAME using the alias name BlocksStreetName.
     * @param value value to set the STREET_NAME
     */
    public void setBlocksStreetName(String value) {
        setAttributeInternal(BLOCKSSTREETNAME, value);
    }

    /**
     * Gets the attribute value for BLOCKFACE_ID using the alias name BlockfaceId.
     * @return the BLOCKFACE_ID
     */
    public Number getBlockfaceId() {
        return (Number) getAttributeInternal(BLOCKFACEID);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOCKFACE_ID using the alias name BlockfaceId.
     * @param value value to set the BLOCKFACE_ID
     */
    public void setBlockfaceId(Number value) {
        setAttributeInternal(BLOCKFACEID, value);
    }

    /**
     * Gets the attribute value for SDE_ID using the alias name BlockfaceSdeId.
     * @return the SDE_ID
     */
    public Number getBlockfaceSdeId() {
        return (Number) getAttributeInternal(BLOCKFACESDEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SDE_ID using the alias name BlockfaceSdeId.
     * @param value value to set the SDE_ID
     */
    public void setBlockfaceSdeId(Number value) {
        setAttributeInternal(BLOCKFACESDEID, value);
    }

    /**
     * Gets the attribute value for STREET_NAME using the alias name BlockfaceStreetName.
     * @return the STREET_NAME
     */
    public String getBlockfaceStreetName() {
        return (String) getAttributeInternal(BLOCKFACESTREETNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for STREET_NAME using the alias name BlockfaceStreetName.
     * @param value value to set the STREET_NAME
     */
    public void setBlockfaceStreetName(String value) {
        setAttributeInternal(BLOCKFACESTREETNAME, value);
    }

    /**
     * Gets the attribute value for BLOCK_NUM using the alias name BlockfaceBlockNum.
     * @return the BLOCK_NUM
     */
    public Number getBlockfaceBlockNum() {
        return (Number) getAttributeInternal(BLOCKFACEBLOCKNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOCK_NUM using the alias name BlockfaceBlockNum.
     * @param value value to set the BLOCK_NUM
     */
    public void setBlockfaceBlockNum(Number value) {
        setAttributeInternal(BLOCKFACEBLOCKNUM, value);
    }

    /**
     * Gets the attribute value for STR_NUM_PARITY using the alias name BlockfaceStrNumParity.
     * @return the STR_NUM_PARITY
     */
    public String getBlockfaceStrNumParity() {
        return (String) getAttributeInternal(BLOCKFACESTRNUMPARITY);
    }

    /**
     * Sets <code>value</code> as attribute value for STR_NUM_PARITY using the alias name BlockfaceStrNumParity.
     * @param value value to set the STR_NUM_PARITY
     */
    public void setBlockfaceStrNumParity(String value) {
        setAttributeInternal(BLOCKFACESTRNUMPARITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedForDeletion.
     * @return the SelectedForDeletion
     */
    public Boolean getSelectedForDeletion() {
        return (Boolean) getAttributeInternal(SELECTEDFORDELETION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedForDeletion.
     * @param value value to set the  SelectedForDeletion
     */
    public void setSelectedForDeletion(Boolean value) {
        setAttributeInternal(SELECTEDFORDELETION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
