package model.bulkeditgroups.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 09 11:55:12 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BlockGroupsUpdtVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BlockGroupsUpdtVOImpl() {
    }
}
