package model.bulkeditgroups.views;

import model.bulkeditgroups.entities.common.SdoGeometry;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 10:08:37 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BlocksRoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BlockId {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getBlockId();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setBlockId((Number)value);
            }
        }
        ,
        AreaType {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getAreaType();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setAreaType((String)value);
            }
        }
        ,
        PmDistrictId {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getPmDistrictId();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setPmDistrictId((Number)value);
            }
        }
        ,
        PmDistrictName {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getPmDistrictName();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setPmDistrictName((String)value);
            }
        }
        ,
        BlockNum {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getBlockNum();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setBlockNum((Number)value);
            }
        }
        ,
        StreetId {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getStreetId();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setStreetId((Number)value);
            }
        }
        ,
        StreetName {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getStreetName();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setStreetName((String)value);
            }
        }
        ,
        BlockDesc {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getBlockDesc();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setBlockDesc((String)value);
            }
        }
        ,
        FmAddrNo {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getFmAddrNo();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setFmAddrNo((Number)value);
            }
        }
        ,
        ToAddrNo {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getToAddrNo();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setToAddrNo((Number)value);
            }
        }
        ,
        Geom {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getGeom();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setGeom((SdoGeometry)value);
            }
        }
        ,
        CreatedDt {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getCreatedDt();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setCreatedDt((Date)value);
            }
        }
        ,
        LastUpdDt {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getLastUpdDt();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setLastUpdDt((Date)value);
            }
        }
        ,
        LastUpdUser {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getLastUpdUser();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setLastUpdUser((String)value);
            }
        }
        ,
        LastUpdPgm {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getLastUpdPgm();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setLastUpdPgm((String)value);
            }
        }
        ,
        SdeId {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getSdeId();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setSdeId((Number)value);
            }
        }
        ,
        NeighborhoodId {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getNeighborhoodId();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setNeighborhoodId((Number)value);
            }
        }
        ,
        NeighborhoodName {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getNeighborhoodName();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setNeighborhoodName((String)value);
            }
        }
        ,
        SelectedBlockRow {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getSelectedBlockRow();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setSelectedBlockRow((Boolean)value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_AreaTypeLovVO {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_AreaTypeLovVO();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_PmDistrictsLovVO {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getGroupsCommonAM_PmDistrictsLovVO();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_Blocks_StreetBlockLovVO {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getGroupsCommonAM_Blocks_StreetBlockLovVO();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_Neighborhoods_NeighborhoodLovVO {
            public Object get(BlocksRoVORowImpl obj) {
                return obj.getGroupsCommonAM_Neighborhoods_NeighborhoodLovVO();
            }

            public void put(BlocksRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BlocksRoVORowImpl object);

        public abstract void put(BlocksRoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BLOCKID = AttributesEnum.BlockId.index();
    public static final int AREATYPE = AttributesEnum.AreaType.index();
    public static final int PMDISTRICTID = AttributesEnum.PmDistrictId.index();
    public static final int PMDISTRICTNAME = AttributesEnum.PmDistrictName.index();
    public static final int BLOCKNUM = AttributesEnum.BlockNum.index();
    public static final int STREETID = AttributesEnum.StreetId.index();
    public static final int STREETNAME = AttributesEnum.StreetName.index();
    public static final int BLOCKDESC = AttributesEnum.BlockDesc.index();
    public static final int FMADDRNO = AttributesEnum.FmAddrNo.index();
    public static final int TOADDRNO = AttributesEnum.ToAddrNo.index();
    public static final int GEOM = AttributesEnum.Geom.index();
    public static final int CREATEDDT = AttributesEnum.CreatedDt.index();
    public static final int LASTUPDDT = AttributesEnum.LastUpdDt.index();
    public static final int LASTUPDUSER = AttributesEnum.LastUpdUser.index();
    public static final int LASTUPDPGM = AttributesEnum.LastUpdPgm.index();
    public static final int SDEID = AttributesEnum.SdeId.index();
    public static final int NEIGHBORHOODID = AttributesEnum.NeighborhoodId.index();
    public static final int NEIGHBORHOODNAME = AttributesEnum.NeighborhoodName.index();
    public static final int SELECTEDBLOCKROW = AttributesEnum.SelectedBlockRow.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_AREATYPELOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_AreaTypeLovVO.index();
    public static final int GROUPSCOMMONAM_PMDISTRICTSLOVVO = AttributesEnum.GroupsCommonAM_PmDistrictsLovVO.index();
    public static final int GROUPSCOMMONAM_BLOCKS_STREETBLOCKLOVVO = AttributesEnum.GroupsCommonAM_Blocks_StreetBlockLovVO.index();
    public static final int GROUPSCOMMONAM_NEIGHBORHOODS_NEIGHBORHOODLOVVO = AttributesEnum.GroupsCommonAM_Neighborhoods_NeighborhoodLovVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BlocksRoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BlockId.
     * @return the BlockId
     */
    public Number getBlockId() {
        return (Number) getAttributeInternal(BLOCKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockId.
     * @param value value to set the  BlockId
     */
    public void setBlockId(Number value) {
        setAttributeInternal(BLOCKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AreaType.
     * @return the AreaType
     */
    public String getAreaType() {
        return (String) getAttributeInternal(AREATYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AreaType.
     * @param value value to set the  AreaType
     */
    public void setAreaType(String value) {
        setAttributeInternal(AREATYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmDistrictId.
     * @return the PmDistrictId
     */
    public Number getPmDistrictId() {
        return (Number) getAttributeInternal(PMDISTRICTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmDistrictId.
     * @param value value to set the  PmDistrictId
     */
    public void setPmDistrictId(Number value) {
        setAttributeInternal(PMDISTRICTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmDistrictName.
     * @return the PmDistrictName
     */
    public String getPmDistrictName() {
        return (String) getAttributeInternal(PMDISTRICTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmDistrictName.
     * @param value value to set the  PmDistrictName
     */
    public void setPmDistrictName(String value) {
        setAttributeInternal(PMDISTRICTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BlockNum.
     * @return the BlockNum
     */
    public Number getBlockNum() {
        return (Number) getAttributeInternal(BLOCKNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockNum.
     * @param value value to set the  BlockNum
     */
    public void setBlockNum(Number value) {
        setAttributeInternal(BLOCKNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetId.
     * @return the StreetId
     */
    public Number getStreetId() {
        return (Number) getAttributeInternal(STREETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetId.
     * @param value value to set the  StreetId
     */
    public void setStreetId(Number value) {
        setAttributeInternal(STREETID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetName.
     * @return the StreetName
     */
    public String getStreetName() {
        return (String) getAttributeInternal(STREETNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetName.
     * @param value value to set the  StreetName
     */
    public void setStreetName(String value) {
        setAttributeInternal(STREETNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BlockDesc.
     * @return the BlockDesc
     */
    public String getBlockDesc() {
        return (String) getAttributeInternal(BLOCKDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockDesc.
     * @param value value to set the  BlockDesc
     */
    public void setBlockDesc(String value) {
        setAttributeInternal(BLOCKDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FmAddrNo.
     * @return the FmAddrNo
     */
    public Number getFmAddrNo() {
        return (Number) getAttributeInternal(FMADDRNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FmAddrNo.
     * @param value value to set the  FmAddrNo
     */
    public void setFmAddrNo(Number value) {
        setAttributeInternal(FMADDRNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ToAddrNo.
     * @return the ToAddrNo
     */
    public Number getToAddrNo() {
        return (Number) getAttributeInternal(TOADDRNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ToAddrNo.
     * @param value value to set the  ToAddrNo
     */
    public void setToAddrNo(Number value) {
        setAttributeInternal(TOADDRNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Geom.
     * @return the Geom
     */
    public SdoGeometry getGeom() {
        return (SdoGeometry)getAttributeInternal(GEOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Geom.
     * @param value value to set the  Geom
     */
    public void setGeom(SdoGeometry value) {
        setAttributeInternal(GEOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDt.
     * @return the CreatedDt
     */
    public Date getCreatedDt() {
        return (Date) getAttributeInternal(CREATEDDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDt.
     * @param value value to set the  CreatedDt
     */
    public void setCreatedDt(Date value) {
        setAttributeInternal(CREATEDDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdDt.
     * @return the LastUpdDt
     */
    public Date getLastUpdDt() {
        return (Date) getAttributeInternal(LASTUPDDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdDt.
     * @param value value to set the  LastUpdDt
     */
    public void setLastUpdDt(Date value) {
        setAttributeInternal(LASTUPDDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdUser.
     * @return the LastUpdUser
     */
    public String getLastUpdUser() {
        return (String) getAttributeInternal(LASTUPDUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdUser.
     * @param value value to set the  LastUpdUser
     */
    public void setLastUpdUser(String value) {
        setAttributeInternal(LASTUPDUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdPgm.
     * @return the LastUpdPgm
     */
    public String getLastUpdPgm() {
        return (String) getAttributeInternal(LASTUPDPGM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdPgm.
     * @param value value to set the  LastUpdPgm
     */
    public void setLastUpdPgm(String value) {
        setAttributeInternal(LASTUPDPGM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SdeId.
     * @return the SdeId
     */
    public Number getSdeId() {
        return (Number) getAttributeInternal(SDEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SdeId.
     * @param value value to set the  SdeId
     */
    public void setSdeId(Number value) {
        setAttributeInternal(SDEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NeighborhoodId.
     * @return the NeighborhoodId
     */
    public Number getNeighborhoodId() {
        return (Number) getAttributeInternal(NEIGHBORHOODID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NeighborhoodId.
     * @param value value to set the  NeighborhoodId
     */
    public void setNeighborhoodId(Number value) {
        setAttributeInternal(NEIGHBORHOODID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NeighborhoodName.
     * @return the NeighborhoodName
     */
    public String getNeighborhoodName() {
        return (String) getAttributeInternal(NEIGHBORHOODNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NeighborhoodName.
     * @param value value to set the  NeighborhoodName
     */
    public void setNeighborhoodName(String value) {
        setAttributeInternal(NEIGHBORHOODNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedBlockRow.
     * @return the SelectedBlockRow
     */
    public Boolean getSelectedBlockRow() {
        return (Boolean) getAttributeInternal(SELECTEDBLOCKROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedBlockRow.
     * @param value value to set the  SelectedBlockRow
     */
    public void setSelectedBlockRow(Boolean value) {
        setAttributeInternal(SELECTEDBLOCKROW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_AreaTypeLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_AreaTypeLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_AREATYPELOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_PmDistrictsLovVO.
     */
    public RowSet getGroupsCommonAM_PmDistrictsLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PMDISTRICTSLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_Blocks_StreetBlockLovVO.
     */
    public RowSet getGroupsCommonAM_Blocks_StreetBlockLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_BLOCKS_STREETBLOCKLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_Neighborhoods_NeighborhoodLovVO.
     */
    public RowSet getGroupsCommonAM_Neighborhoods_NeighborhoodLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_NEIGHBORHOODS_NEIGHBORHOODLOVVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
