package model.bulkeditgroups.views;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 09:03:54 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MeterOpScheduleRoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        MeterOpSchedId {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getMeterOpSchedId();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setMeterOpSchedId((Number)value);
            }
        }
        ,
        ParkingSpaceId {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getParkingSpaceId();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setParkingSpaceId((Number)value);
            }
        }
        ,
        SchedType {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getSchedType();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setSchedType((String)value);
            }
        }
        ,
        EffFromDt {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getEffFromDt();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setEffFromDt((Date)value);
            }
        }
        ,
        EffToDt {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getEffToDt();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setEffToDt((Date)value);
            }
        }
        ,
        ColorRuleApplied {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getColorRuleApplied();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setColorRuleApplied((String)value);
            }
        }
        ,
        AltAddlDesc {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getAltAddlDesc();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAltAddlDesc((String)value);
            }
        }
        ,
        FromTime {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getFromTime();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setFromTime((Number)value);
            }
        }
        ,
        ToTime {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getToTime();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setToTime((Number)value);
            }
        }
        ,
        DaysApplied {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getDaysApplied();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setDaysApplied((String)value);
            }
        }
        ,
        TimeLimit {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getTimeLimit();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setTimeLimit((Number)value);
            }
        }
        ,
        Timelimitdesc {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getTimelimitdesc();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setTimelimitdesc((String)value);
            }
        }
        ,
        PrepaymentTime {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getPrepaymentTime();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setPrepaymentTime((Number)value);
            }
        }
        ,
        Prepaymenttimedesc {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getPrepaymenttimedesc();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setPrepaymenttimedesc((String)value);
            }
        }
        ,
        PostId {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getPostId();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setPostId((String)value);
            }
        }
        ,
        MsPayStationId {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getMsPayStationId();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setMsPayStationId((String)value);
            }
        }
        ,
        MsSpaceNum {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getMsSpaceNum();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setMsSpaceNum((Number)value);
            }
        }
        ,
        SensorFlag {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getSensorFlag();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setSensorFlag((String)value);
            }
        }
        ,
        OnOffstreetType {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getOnOffstreetType();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setOnOffstreetType((String)value);
            }
        }
        ,
        Jurisdiction {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getJurisdiction();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setJurisdiction((String)value);
            }
        }
        ,
        PmDistrictName {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getPmDistrictName();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setPmDistrictName((String)value);
            }
        }
        ,
        BlockfaceId {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getBlockfaceId();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setBlockfaceId((Number)value);
            }
        }
        ,
        ActiveMeterFlag {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getActiveMeterFlag();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setActiveMeterFlag((String)value);
            }
        }
        ,
        SmartMeterFlag {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getSmartMeterFlag();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setSmartMeterFlag((String)value);
            }
        }
        ,
        MeterType {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getMeterType();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setMeterType((String)value);
            }
        }
        ,
        MeterVendor {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getMeterVendor();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setMeterVendor((String)value);
            }
        }
        ,
        MeterModel {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getMeterModel();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setMeterModel((String)value);
            }
        }
        ,
        CapColor {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getCapColor();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setCapColor((String)value);
            }
        }
        ,
        PcoBeat {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getPcoBeat();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setPcoBeat((String)value);
            }
        }
        ,
        OldRateArea {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getOldRateArea();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setOldRateArea((String)value);
            }
        }
        ,
        StreetBlock {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getStreetBlock();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setStreetBlock((String)value);
            }
        }
        ,
        SelectedMeterOpScheduleRow {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getSelectedMeterOpScheduleRow();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setSelectedMeterOpScheduleRow((Boolean)value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_CapColorLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_CapColorLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_MeterModelLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_MeterModelLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_MeterVendorLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_MeterVendorLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_MeterTypeLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_MeterTypeLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_SmartMeterFlagLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_SmartMeterFlagLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_PmDistrictsLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_PmDistrictsLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_JurisdictionLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_JurisdictionLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_SensorFlagLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_SensorFlagLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_ScheduleTypeLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_ScheduleTypeLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_ColorRuleAppliedLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_ColorRuleAppliedLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterOpSched_DaysAppliedLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterOpSched_DaysAppliedLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterOpSched_AltAddlSchedLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterOpSched_AltAddlSchedLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterOpSched_FromTimeLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterOpSched_FromTimeLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterOpSched_ToTimeLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterOpSched_ToTimeLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_TimeLimitLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_TimeLimitLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_PrePaymentTimeLovVO1 {
            public Object get(MeterOpScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_PrePaymentTimeLovVO1();
            }

            public void put(MeterOpScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MeterOpScheduleRoVORowImpl object);

        public abstract void put(MeterOpScheduleRoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int METEROPSCHEDID = AttributesEnum.MeterOpSchedId.index();
    public static final int PARKINGSPACEID = AttributesEnum.ParkingSpaceId.index();
    public static final int SCHEDTYPE = AttributesEnum.SchedType.index();
    public static final int EFFFROMDT = AttributesEnum.EffFromDt.index();
    public static final int EFFTODT = AttributesEnum.EffToDt.index();
    public static final int COLORRULEAPPLIED = AttributesEnum.ColorRuleApplied.index();
    public static final int ALTADDLDESC = AttributesEnum.AltAddlDesc.index();
    public static final int FROMTIME = AttributesEnum.FromTime.index();
    public static final int TOTIME = AttributesEnum.ToTime.index();
    public static final int DAYSAPPLIED = AttributesEnum.DaysApplied.index();
    public static final int TIMELIMIT = AttributesEnum.TimeLimit.index();
    public static final int TIMELIMITDESC = AttributesEnum.Timelimitdesc.index();
    public static final int PREPAYMENTTIME = AttributesEnum.PrepaymentTime.index();
    public static final int PREPAYMENTTIMEDESC = AttributesEnum.Prepaymenttimedesc.index();
    public static final int POSTID = AttributesEnum.PostId.index();
    public static final int MSPAYSTATIONID = AttributesEnum.MsPayStationId.index();
    public static final int MSSPACENUM = AttributesEnum.MsSpaceNum.index();
    public static final int SENSORFLAG = AttributesEnum.SensorFlag.index();
    public static final int ONOFFSTREETTYPE = AttributesEnum.OnOffstreetType.index();
    public static final int JURISDICTION = AttributesEnum.Jurisdiction.index();
    public static final int PMDISTRICTNAME = AttributesEnum.PmDistrictName.index();
    public static final int BLOCKFACEID = AttributesEnum.BlockfaceId.index();
    public static final int ACTIVEMETERFLAG = AttributesEnum.ActiveMeterFlag.index();
    public static final int SMARTMETERFLAG = AttributesEnum.SmartMeterFlag.index();
    public static final int METERTYPE = AttributesEnum.MeterType.index();
    public static final int METERVENDOR = AttributesEnum.MeterVendor.index();
    public static final int METERMODEL = AttributesEnum.MeterModel.index();
    public static final int CAPCOLOR = AttributesEnum.CapColor.index();
    public static final int PCOBEAT = AttributesEnum.PcoBeat.index();
    public static final int OLDRATEAREA = AttributesEnum.OldRateArea.index();
    public static final int STREETBLOCK = AttributesEnum.StreetBlock.index();
    public static final int SELECTEDMETEROPSCHEDULEROW = AttributesEnum.SelectedMeterOpScheduleRow.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_STREETBLOCKLOVVO1 = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_OLDRATEAREALOVVO1 = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_PCOBEATLOVVO1 = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_CAPCOLORLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_CapColorLovVO1.index();
    public static final int GROUPSCOMMONAM_METERMODELS_METERMODELLOVVO1 = AttributesEnum.GroupsCommonAM_MeterModels_MeterModelLovVO1.index();
    public static final int GROUPSCOMMONAM_METERMODELS_METERVENDORLOVVO1 = AttributesEnum.GroupsCommonAM_MeterModels_MeterVendorLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_METERTYPELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_MeterTypeLovVO1.index();
    public static final int GROUPSCOMMONAM_METERMODELS_SMARTMETERFLAGLOVVO1 = AttributesEnum.GroupsCommonAM_MeterModels_SmartMeterFlagLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_ACTIVEMETERFLAGLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1.index();
    public static final int GROUPSCOMMONAM_PMDISTRICTSLOVVO1 = AttributesEnum.GroupsCommonAM_PmDistrictsLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_JURISDICTIONLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_JurisdictionLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_ONOFFSTREETTYPELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_SENSORFLAGLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_SensorFlagLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_SCHEDULETYPELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_ScheduleTypeLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_COLORRULEAPPLIEDLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_ColorRuleAppliedLovVO1.index();
    public static final int GROUPSCOMMONAM_METEROPSCHED_DAYSAPPLIEDLOVVO1 = AttributesEnum.GroupsCommonAM_MeterOpSched_DaysAppliedLovVO1.index();
    public static final int GROUPSCOMMONAM_METEROPSCHED_ALTADDLSCHEDLOVVO1 = AttributesEnum.GroupsCommonAM_MeterOpSched_AltAddlSchedLovVO1.index();
    public static final int GROUPSCOMMONAM_METEROPSCHED_FROMTIMELOVVO1 = AttributesEnum.GroupsCommonAM_MeterOpSched_FromTimeLovVO1.index();
    public static final int GROUPSCOMMONAM_METEROPSCHED_TOTIMELOVVO1 = AttributesEnum.GroupsCommonAM_MeterOpSched_ToTimeLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_TIMELIMITLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_TimeLimitLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_PREPAYMENTTIMELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_PrePaymentTimeLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MeterOpScheduleRoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute MeterOpSchedId.
     * @return the MeterOpSchedId
     */
    public Number getMeterOpSchedId() {
        return (Number) getAttributeInternal(METEROPSCHEDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterOpSchedId.
     * @param value value to set the  MeterOpSchedId
     */
    public void setMeterOpSchedId(Number value) {
        setAttributeInternal(METEROPSCHEDID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParkingSpaceId.
     * @return the ParkingSpaceId
     */
    public Number getParkingSpaceId() {
        return (Number) getAttributeInternal(PARKINGSPACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParkingSpaceId.
     * @param value value to set the  ParkingSpaceId
     */
    public void setParkingSpaceId(Number value) {
        setAttributeInternal(PARKINGSPACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SchedType.
     * @return the SchedType
     */
    public String getSchedType() {
        return (String) getAttributeInternal(SCHEDTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SchedType.
     * @param value value to set the  SchedType
     */
    public void setSchedType(String value) {
        setAttributeInternal(SCHEDTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffFromDt.
     * @return the EffFromDt
     */
    public Date getEffFromDt() {
        return (Date) getAttributeInternal(EFFFROMDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffFromDt.
     * @param value value to set the  EffFromDt
     */
    public void setEffFromDt(Date value) {
        setAttributeInternal(EFFFROMDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffToDt.
     * @return the EffToDt
     */
    public Date getEffToDt() {
        return (Date) getAttributeInternal(EFFTODT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffToDt.
     * @param value value to set the  EffToDt
     */
    public void setEffToDt(Date value) {
        setAttributeInternal(EFFTODT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ColorRuleApplied.
     * @return the ColorRuleApplied
     */
    public String getColorRuleApplied() {
        return (String) getAttributeInternal(COLORRULEAPPLIED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ColorRuleApplied.
     * @param value value to set the  ColorRuleApplied
     */
    public void setColorRuleApplied(String value) {
        setAttributeInternal(COLORRULEAPPLIED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AltAddlDesc.
     * @return the AltAddlDesc
     */
    public String getAltAddlDesc() {
        return (String) getAttributeInternal(ALTADDLDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AltAddlDesc.
     * @param value value to set the  AltAddlDesc
     */
    public void setAltAddlDesc(String value) {
        setAttributeInternal(ALTADDLDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FromTime.
     * @return the FromTime
     */
    public Number getFromTime() {
        return (Number) getAttributeInternal(FROMTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FromTime.
     * @param value value to set the  FromTime
     */
    public void setFromTime(Number value) {
        setAttributeInternal(FROMTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ToTime.
     * @return the ToTime
     */
    public Number getToTime() {
        return (Number) getAttributeInternal(TOTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ToTime.
     * @param value value to set the  ToTime
     */
    public void setToTime(Number value) {
        setAttributeInternal(TOTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DaysApplied.
     * @return the DaysApplied
     */
    public String getDaysApplied() {
        return (String) getAttributeInternal(DAYSAPPLIED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DaysApplied.
     * @param value value to set the  DaysApplied
     */
    public void setDaysApplied(String value) {
        setAttributeInternal(DAYSAPPLIED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TimeLimit.
     * @return the TimeLimit
     */
    public Number getTimeLimit() {
        return (Number) getAttributeInternal(TIMELIMIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TimeLimit.
     * @param value value to set the  TimeLimit
     */
    public void setTimeLimit(Number value) {
        setAttributeInternal(TIMELIMIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Timelimitdesc.
     * @return the Timelimitdesc
     */
    public String getTimelimitdesc() {
        return (String) getAttributeInternal(TIMELIMITDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Timelimitdesc.
     * @param value value to set the  Timelimitdesc
     */
    public void setTimelimitdesc(String value) {
        setAttributeInternal(TIMELIMITDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrepaymentTime.
     * @return the PrepaymentTime
     */
    public Number getPrepaymentTime() {
        return (Number) getAttributeInternal(PREPAYMENTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrepaymentTime.
     * @param value value to set the  PrepaymentTime
     */
    public void setPrepaymentTime(Number value) {
        setAttributeInternal(PREPAYMENTTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Prepaymenttimedesc.
     * @return the Prepaymenttimedesc
     */
    public String getPrepaymenttimedesc() {
        return (String) getAttributeInternal(PREPAYMENTTIMEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Prepaymenttimedesc.
     * @param value value to set the  Prepaymenttimedesc
     */
    public void setPrepaymenttimedesc(String value) {
        setAttributeInternal(PREPAYMENTTIMEDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PostId.
     * @return the PostId
     */
    public String getPostId() {
        return (String) getAttributeInternal(POSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PostId.
     * @param value value to set the  PostId
     */
    public void setPostId(String value) {
        setAttributeInternal(POSTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsPayStationId.
     * @return the MsPayStationId
     */
    public String getMsPayStationId() {
        return (String) getAttributeInternal(MSPAYSTATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsPayStationId.
     * @param value value to set the  MsPayStationId
     */
    public void setMsPayStationId(String value) {
        setAttributeInternal(MSPAYSTATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsSpaceNum.
     * @return the MsSpaceNum
     */
    public Number getMsSpaceNum() {
        return (Number) getAttributeInternal(MSSPACENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsSpaceNum.
     * @param value value to set the  MsSpaceNum
     */
    public void setMsSpaceNum(Number value) {
        setAttributeInternal(MSSPACENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SensorFlag.
     * @return the SensorFlag
     */
    public String getSensorFlag() {
        return (String) getAttributeInternal(SENSORFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SensorFlag.
     * @param value value to set the  SensorFlag
     */
    public void setSensorFlag(String value) {
        setAttributeInternal(SENSORFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OnOffstreetType.
     * @return the OnOffstreetType
     */
    public String getOnOffstreetType() {
        return (String) getAttributeInternal(ONOFFSTREETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OnOffstreetType.
     * @param value value to set the  OnOffstreetType
     */
    public void setOnOffstreetType(String value) {
        setAttributeInternal(ONOFFSTREETTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Jurisdiction.
     * @return the Jurisdiction
     */
    public String getJurisdiction() {
        return (String) getAttributeInternal(JURISDICTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Jurisdiction.
     * @param value value to set the  Jurisdiction
     */
    public void setJurisdiction(String value) {
        setAttributeInternal(JURISDICTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmDistrictName.
     * @return the PmDistrictName
     */
    public String getPmDistrictName() {
        return (String) getAttributeInternal(PMDISTRICTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmDistrictName.
     * @param value value to set the  PmDistrictName
     */
    public void setPmDistrictName(String value) {
        setAttributeInternal(PMDISTRICTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BlockfaceId.
     * @return the BlockfaceId
     */
    public Number getBlockfaceId() {
        return (Number) getAttributeInternal(BLOCKFACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockfaceId.
     * @param value value to set the  BlockfaceId
     */
    public void setBlockfaceId(Number value) {
        setAttributeInternal(BLOCKFACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveMeterFlag.
     * @return the ActiveMeterFlag
     */
    public String getActiveMeterFlag() {
        return (String) getAttributeInternal(ACTIVEMETERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveMeterFlag.
     * @param value value to set the  ActiveMeterFlag
     */
    public void setActiveMeterFlag(String value) {
        setAttributeInternal(ACTIVEMETERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SmartMeterFlag.
     * @return the SmartMeterFlag
     */
    public String getSmartMeterFlag() {
        return (String) getAttributeInternal(SMARTMETERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SmartMeterFlag.
     * @param value value to set the  SmartMeterFlag
     */
    public void setSmartMeterFlag(String value) {
        setAttributeInternal(SMARTMETERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterType.
     * @return the MeterType
     */
    public String getMeterType() {
        return (String) getAttributeInternal(METERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterType.
     * @param value value to set the  MeterType
     */
    public void setMeterType(String value) {
        setAttributeInternal(METERTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterVendor.
     * @return the MeterVendor
     */
    public String getMeterVendor() {
        return (String) getAttributeInternal(METERVENDOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterVendor.
     * @param value value to set the  MeterVendor
     */
    public void setMeterVendor(String value) {
        setAttributeInternal(METERVENDOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterModel.
     * @return the MeterModel
     */
    public String getMeterModel() {
        return (String) getAttributeInternal(METERMODEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterModel.
     * @param value value to set the  MeterModel
     */
    public void setMeterModel(String value) {
        setAttributeInternal(METERMODEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CapColor.
     * @return the CapColor
     */
    public String getCapColor() {
        return (String) getAttributeInternal(CAPCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CapColor.
     * @param value value to set the  CapColor
     */
    public void setCapColor(String value) {
        setAttributeInternal(CAPCOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PcoBeat.
     * @return the PcoBeat
     */
    public String getPcoBeat() {
        return (String) getAttributeInternal(PCOBEAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PcoBeat.
     * @param value value to set the  PcoBeat
     */
    public void setPcoBeat(String value) {
        setAttributeInternal(PCOBEAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OldRateArea.
     * @return the OldRateArea
     */
    public String getOldRateArea() {
        return (String) getAttributeInternal(OLDRATEAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OldRateArea.
     * @param value value to set the  OldRateArea
     */
    public void setOldRateArea(String value) {
        setAttributeInternal(OLDRATEAREA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetBlock.
     * @return the StreetBlock
     */
    public String getStreetBlock() {
        return (String) getAttributeInternal(STREETBLOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetBlock.
     * @param value value to set the  StreetBlock
     */
    public void setStreetBlock(String value) {
        setAttributeInternal(STREETBLOCK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedMeterOpScheduleRow.
     * @return the SelectedMeterOpScheduleRow
     */
    public Boolean getSelectedMeterOpScheduleRow() {
        return (Boolean) getAttributeInternal(SELECTEDMETEROPSCHEDULEROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedMeterOpScheduleRow.
     * @param value value to set the  SelectedMeterOpScheduleRow
     */
    public void setSelectedMeterOpScheduleRow(Boolean value) {
        setAttributeInternal(SELECTEDMETEROPSCHEDULEROW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_STREETBLOCKLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_OLDRATEAREALOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_PCOBEATLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_CapColorLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_CapColorLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_CAPCOLORLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_MeterModelLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterModels_MeterModelLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_METERMODELLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_MeterVendorLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterModels_MeterVendorLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_METERVENDORLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_MeterTypeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_MeterTypeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_METERTYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_SmartMeterFlagLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterModels_SmartMeterFlagLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_SMARTMETERFLAGLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_ACTIVEMETERFLAGLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_PmDistrictsLovVO1.
     */
    public RowSet getGroupsCommonAM_PmDistrictsLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PMDISTRICTSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_JurisdictionLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_JurisdictionLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_JURISDICTIONLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_ONOFFSTREETTYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_SensorFlagLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_SensorFlagLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_SENSORFLAGLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_ScheduleTypeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_ScheduleTypeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_SCHEDULETYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_ColorRuleAppliedLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_ColorRuleAppliedLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_COLORRULEAPPLIEDLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterOpSched_DaysAppliedLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterOpSched_DaysAppliedLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METEROPSCHED_DAYSAPPLIEDLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterOpSched_AltAddlSchedLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterOpSched_AltAddlSchedLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METEROPSCHED_ALTADDLSCHEDLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterOpSched_FromTimeLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterOpSched_FromTimeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METEROPSCHED_FROMTIMELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterOpSched_ToTimeLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterOpSched_ToTimeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METEROPSCHED_TOTIMELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_TimeLimitLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_TimeLimitLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_TIMELIMITLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_PrePaymentTimeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_PrePaymentTimeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_PREPAYMENTTIMELOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
