package model.bulkeditgroups.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 09:03:54 CDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MeterOpScheduleRoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MeterOpScheduleRoVOImpl() {
    }
}
