package model.bulkeditgroups.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 14 10:51:46 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParkingSpaceInventoryRoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ParkingSpaceInventoryRoVOImpl() {
    }
}
