package model.bulkeditgroups.views;

import model.bulkeditgroups.entities.common.SdoGeometry;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 14 10:51:45 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParkingSpaceInventoryRoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ParkingSpaceId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getParkingSpaceId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setParkingSpaceId((Number)value);
            }
        }
        ,
        PostId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getPostId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setPostId((String)value);
            }
        }
        ,
        MsPayStationId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getMsPayStationId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setMsPayStationId((String)value);
            }
        }
        ,
        MsSpaceNum {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getMsSpaceNum();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setMsSpaceNum((Number)value);
            }
        }
        ,
        SensorFlag {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getSensorFlag();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setSensorFlag((String)value);
            }
        }
        ,
        SensorDescription {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getSensorDescription();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setSensorDescription((String)value);
            }
        }
        ,
        OnOffstreetType {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getOnOffstreetType();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setOnOffstreetType((String)value);
            }
        }
        ,
        OspId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getOspId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setOspId((Number)value);
            }
        }
        ,
        FacilityName {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getFacilityName();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setFacilityName((String)value);
            }
        }
        ,
        Jurisdiction {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getJurisdiction();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setJurisdiction((String)value);
            }
        }
        ,
        PmDistrictId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getPmDistrictId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setPmDistrictId((Number)value);
            }
        }
        ,
        PmDistrictName {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getPmDistrictName();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setPmDistrictName((String)value);
            }
        }
        ,
        BlockfaceId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getBlockfaceId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setBlockfaceId((Number)value);
            }
        }
        ,
        ActiveMeterFlag {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getActiveMeterFlag();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setActiveMeterFlag((String)value);
            }
        }
        ,
        ActiveMeterDesc {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getActiveMeterDesc();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setActiveMeterDesc((String)value);
            }
        }
        ,
        ReasonCode {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getReasonCode();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setReasonCode((String)value);
            }
        }
        ,
        SmartMeterFlag {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getSmartMeterFlag();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setSmartMeterFlag((String)value);
            }
        }
        ,
        MeterType {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getMeterType();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setMeterType((String)value);
            }
        }
        ,
        MeterVendor {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getMeterVendor();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setMeterVendor((String)value);
            }
        }
        ,
        MeterModel {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getMeterModel();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setMeterModel((String)value);
            }
        }
        ,
        CapColor {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getCapColor();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setCapColor((String)value);
            }
        }
        ,
        CapColorDesc {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getCapColorDesc();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setCapColorDesc((String)value);
            }
        }
        ,
        PcoBeat {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getPcoBeat();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setPcoBeat((String)value);
            }
        }
        ,
        OldRateArea {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getOldRateArea();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setOldRateArea((String)value);
            }
        }
        ,
        StreetId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getStreetId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setStreetId((Number)value);
            }
        }
        ,
        StreetName {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getStreetName();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setStreetName((String)value);
            }
        }
        ,
        StreetNum {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getStreetNum();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setStreetNum((Number)value);
            }
        }
        ,
        ParityDigitPosition {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getParityDigitPosition();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setParityDigitPosition((String)value);
            }
        }
        ,
        StreetSegCtrlnId {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getStreetSegCtrlnId();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setStreetSegCtrlnId((Number)value);
            }
        }
        ,
        Orientation {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getOrientation();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setOrientation((Number)value);
            }
        }
        ,
        Longitude {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLongitude();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLongitude((Number)value);
            }
        }
        ,
        Latitude {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLatitude();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLatitude((Number)value);
            }
        }
        ,
        Geom {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGeom();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setGeom((SdoGeometry)value);
            }
        }
        ,
        LegislationRef {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLegislationRef();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLegislationRef((String)value);
            }
        }
        ,
        LegislationDt {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLegislationDt();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLegislationDt((Date)value);
            }
        }
        ,
        WorkOrder {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getWorkOrder();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setWorkOrder((String)value);
            }
        }
        ,
        Comments {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getComments();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        CreatedDt {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getCreatedDt();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setCreatedDt((Date)value);
            }
        }
        ,
        LastUpdDt {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLastUpdDt();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLastUpdDt((Date)value);
            }
        }
        ,
        LastUpdUser {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLastUpdUser();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLastUpdUser((String)value);
            }
        }
        ,
        LastUpdPgm {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getLastUpdPgm();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setLastUpdPgm((String)value);
            }
        }
        ,
        CollectionRoute {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getCollectionRoute();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setCollectionRoute((String)value);
            }
        }
        ,
        CollectionSubroute {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getCollectionSubroute();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setCollectionSubroute((String)value);
            }
        }
        ,
        PmrRoute {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getPmrRoute();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setPmrRoute((String)value);
            }
        }
        ,
        BlockNum {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getBlockNum();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setBlockNum((Number)value);
            }
        }
        ,
        StreetBlock {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getStreetBlock();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setStreetBlock((String)value);
            }
        }
        ,
        SelectedParkingSpaceRow {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getSelectedParkingSpaceRow();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setSelectedParkingSpaceRow((Boolean)value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_MsPayStationIdLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_MsPayStationIdLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_MsSpaceNumLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_MsSpaceNumLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_SensorFlagLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_SensorFlagLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_JurisdictionLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_JurisdictionLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_PmDistrictsLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_PmDistrictsLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_SmartMeterFlagLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_SmartMeterFlagLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_MeterTypeLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_MeterTypeLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_MeterVendorLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_MeterVendorLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_MeterModelLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_MeterModelLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_CapColorLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_CapColorLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_OspInventory_OspIdFacilityNameLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_OspInventory_OspIdFacilityNameLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO {
            public Object get(ParkingSpaceInventoryRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO();
            }

            public void put(ParkingSpaceInventoryRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ParkingSpaceInventoryRoVORowImpl object);

        public abstract void put(ParkingSpaceInventoryRoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PARKINGSPACEID = AttributesEnum.ParkingSpaceId.index();
    public static final int POSTID = AttributesEnum.PostId.index();
    public static final int MSPAYSTATIONID = AttributesEnum.MsPayStationId.index();
    public static final int MSSPACENUM = AttributesEnum.MsSpaceNum.index();
    public static final int SENSORFLAG = AttributesEnum.SensorFlag.index();
    public static final int SENSORDESCRIPTION = AttributesEnum.SensorDescription.index();
    public static final int ONOFFSTREETTYPE = AttributesEnum.OnOffstreetType.index();
    public static final int OSPID = AttributesEnum.OspId.index();
    public static final int FACILITYNAME = AttributesEnum.FacilityName.index();
    public static final int JURISDICTION = AttributesEnum.Jurisdiction.index();
    public static final int PMDISTRICTID = AttributesEnum.PmDistrictId.index();
    public static final int PMDISTRICTNAME = AttributesEnum.PmDistrictName.index();
    public static final int BLOCKFACEID = AttributesEnum.BlockfaceId.index();
    public static final int ACTIVEMETERFLAG = AttributesEnum.ActiveMeterFlag.index();
    public static final int ACTIVEMETERDESC = AttributesEnum.ActiveMeterDesc.index();
    public static final int REASONCODE = AttributesEnum.ReasonCode.index();
    public static final int SMARTMETERFLAG = AttributesEnum.SmartMeterFlag.index();
    public static final int METERTYPE = AttributesEnum.MeterType.index();
    public static final int METERVENDOR = AttributesEnum.MeterVendor.index();
    public static final int METERMODEL = AttributesEnum.MeterModel.index();
    public static final int CAPCOLOR = AttributesEnum.CapColor.index();
    public static final int CAPCOLORDESC = AttributesEnum.CapColorDesc.index();
    public static final int PCOBEAT = AttributesEnum.PcoBeat.index();
    public static final int OLDRATEAREA = AttributesEnum.OldRateArea.index();
    public static final int STREETID = AttributesEnum.StreetId.index();
    public static final int STREETNAME = AttributesEnum.StreetName.index();
    public static final int STREETNUM = AttributesEnum.StreetNum.index();
    public static final int PARITYDIGITPOSITION = AttributesEnum.ParityDigitPosition.index();
    public static final int STREETSEGCTRLNID = AttributesEnum.StreetSegCtrlnId.index();
    public static final int ORIENTATION = AttributesEnum.Orientation.index();
    public static final int LONGITUDE = AttributesEnum.Longitude.index();
    public static final int LATITUDE = AttributesEnum.Latitude.index();
    public static final int GEOM = AttributesEnum.Geom.index();
    public static final int LEGISLATIONREF = AttributesEnum.LegislationRef.index();
    public static final int LEGISLATIONDT = AttributesEnum.LegislationDt.index();
    public static final int WORKORDER = AttributesEnum.WorkOrder.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDDT = AttributesEnum.CreatedDt.index();
    public static final int LASTUPDDT = AttributesEnum.LastUpdDt.index();
    public static final int LASTUPDUSER = AttributesEnum.LastUpdUser.index();
    public static final int LASTUPDPGM = AttributesEnum.LastUpdPgm.index();
    public static final int COLLECTIONROUTE = AttributesEnum.CollectionRoute.index();
    public static final int COLLECTIONSUBROUTE = AttributesEnum.CollectionSubroute.index();
    public static final int PMRROUTE = AttributesEnum.PmrRoute.index();
    public static final int BLOCKNUM = AttributesEnum.BlockNum.index();
    public static final int STREETBLOCK = AttributesEnum.StreetBlock.index();
    public static final int SELECTEDPARKINGSPACEROW = AttributesEnum.SelectedParkingSpaceRow.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_MSPAYSTATIONIDLOVVO = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_MsPayStationIdLovVO.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_MSSPACENUMLOVVO = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_MsSpaceNumLovVO.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_SENSORFLAGLOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_SensorFlagLovVO.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_JURISDICTIONLOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_JurisdictionLovVO.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_ONOFFSTREETTYPELOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO.index();
    public static final int GROUPSCOMMONAM_PMDISTRICTSLOVVO = AttributesEnum.GroupsCommonAM_PmDistrictsLovVO.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_ACTIVEMETERFLAGLOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO.index();
    public static final int GROUPSCOMMONAM_METERMODELS_SMARTMETERFLAGLOVVO = AttributesEnum.GroupsCommonAM_MeterModels_SmartMeterFlagLovVO.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_METERTYPELOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_MeterTypeLovVO.index();
    public static final int GROUPSCOMMONAM_METERMODELS_METERVENDORLOVVO = AttributesEnum.GroupsCommonAM_MeterModels_MeterVendorLovVO.index();
    public static final int GROUPSCOMMONAM_METERMODELS_METERMODELLOVVO = AttributesEnum.GroupsCommonAM_MeterModels_MeterModelLovVO.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_CAPCOLORLOVVO = AttributesEnum.GroupsCommonAM_AllowedValues_CapColorLovVO.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_OLDRATEAREALOVVO = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_STREETBLOCKLOVVO = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO.index();
    public static final int GROUPSCOMMONAM_OSPINVENTORY_OSPIDFACILITYNAMELOVVO = AttributesEnum.GroupsCommonAM_OspInventory_OspIdFacilityNameLovVO.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_PCOBEATLOVVO = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParkingSpaceInventoryRoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ParkingSpaceId.
     * @return the ParkingSpaceId
     */
    public Number getParkingSpaceId() {
        return (Number) getAttributeInternal(PARKINGSPACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParkingSpaceId.
     * @param value value to set the  ParkingSpaceId
     */
    public void setParkingSpaceId(Number value) {
        setAttributeInternal(PARKINGSPACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PostId.
     * @return the PostId
     */
    public String getPostId() {
        return (String) getAttributeInternal(POSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PostId.
     * @param value value to set the  PostId
     */
    public void setPostId(String value) {
        setAttributeInternal(POSTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsPayStationId.
     * @return the MsPayStationId
     */
    public String getMsPayStationId() {
        return (String) getAttributeInternal(MSPAYSTATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsPayStationId.
     * @param value value to set the  MsPayStationId
     */
    public void setMsPayStationId(String value) {
        setAttributeInternal(MSPAYSTATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsSpaceNum.
     * @return the MsSpaceNum
     */
    public Number getMsSpaceNum() {
        return (Number) getAttributeInternal(MSSPACENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsSpaceNum.
     * @param value value to set the  MsSpaceNum
     */
    public void setMsSpaceNum(Number value) {
        setAttributeInternal(MSSPACENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SensorFlag.
     * @return the SensorFlag
     */
    public String getSensorFlag() {
        return (String) getAttributeInternal(SENSORFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SensorFlag.
     * @param value value to set the  SensorFlag
     */
    public void setSensorFlag(String value) {
        setAttributeInternal(SENSORFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SensorDescription.
     * @return the SensorDescription
     */
    public String getSensorDescription() {
        return (String) getAttributeInternal(SENSORDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SensorDescription.
     * @param value value to set the  SensorDescription
     */
    public void setSensorDescription(String value) {
        setAttributeInternal(SENSORDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OnOffstreetType.
     * @return the OnOffstreetType
     */
    public String getOnOffstreetType() {
        return (String) getAttributeInternal(ONOFFSTREETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OnOffstreetType.
     * @param value value to set the  OnOffstreetType
     */
    public void setOnOffstreetType(String value) {
        setAttributeInternal(ONOFFSTREETTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OspId.
     * @return the OspId
     */
    public Number getOspId() {
        return (Number) getAttributeInternal(OSPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OspId.
     * @param value value to set the  OspId
     */
    public void setOspId(Number value) {
        setAttributeInternal(OSPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FacilityName.
     * @return the FacilityName
     */
    public String getFacilityName() {
        return (String) getAttributeInternal(FACILITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FacilityName.
     * @param value value to set the  FacilityName
     */
    public void setFacilityName(String value) {
        setAttributeInternal(FACILITYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Jurisdiction.
     * @return the Jurisdiction
     */
    public String getJurisdiction() {
        return (String) getAttributeInternal(JURISDICTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Jurisdiction.
     * @param value value to set the  Jurisdiction
     */
    public void setJurisdiction(String value) {
        setAttributeInternal(JURISDICTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmDistrictId.
     * @return the PmDistrictId
     */
    public Number getPmDistrictId() {
        return (Number) getAttributeInternal(PMDISTRICTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmDistrictId.
     * @param value value to set the  PmDistrictId
     */
    public void setPmDistrictId(Number value) {
        setAttributeInternal(PMDISTRICTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmDistrictName.
     * @return the PmDistrictName
     */
    public String getPmDistrictName() {
        return (String) getAttributeInternal(PMDISTRICTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmDistrictName.
     * @param value value to set the  PmDistrictName
     */
    public void setPmDistrictName(String value) {
        setAttributeInternal(PMDISTRICTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BlockfaceId.
     * @return the BlockfaceId
     */
    public Number getBlockfaceId() {
        return (Number) getAttributeInternal(BLOCKFACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockfaceId.
     * @param value value to set the  BlockfaceId
     */
    public void setBlockfaceId(Number value) {
        setAttributeInternal(BLOCKFACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveMeterFlag.
     * @return the ActiveMeterFlag
     */
    public String getActiveMeterFlag() {
        return (String) getAttributeInternal(ACTIVEMETERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveMeterFlag.
     * @param value value to set the  ActiveMeterFlag
     */
    public void setActiveMeterFlag(String value) {
        setAttributeInternal(ACTIVEMETERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveMeterDesc.
     * @return the ActiveMeterDesc
     */
    public String getActiveMeterDesc() {
        return (String) getAttributeInternal(ACTIVEMETERDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveMeterDesc.
     * @param value value to set the  ActiveMeterDesc
     */
    public void setActiveMeterDesc(String value) {
        setAttributeInternal(ACTIVEMETERDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReasonCode.
     * @return the ReasonCode
     */
    public String getReasonCode() {
        return (String) getAttributeInternal(REASONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReasonCode.
     * @param value value to set the  ReasonCode
     */
    public void setReasonCode(String value) {
        setAttributeInternal(REASONCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SmartMeterFlag.
     * @return the SmartMeterFlag
     */
    public String getSmartMeterFlag() {
        return (String) getAttributeInternal(SMARTMETERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SmartMeterFlag.
     * @param value value to set the  SmartMeterFlag
     */
    public void setSmartMeterFlag(String value) {
        setAttributeInternal(SMARTMETERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterType.
     * @return the MeterType
     */
    public String getMeterType() {
        return (String) getAttributeInternal(METERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterType.
     * @param value value to set the  MeterType
     */
    public void setMeterType(String value) {
        setAttributeInternal(METERTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterVendor.
     * @return the MeterVendor
     */
    public String getMeterVendor() {
        return (String) getAttributeInternal(METERVENDOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterVendor.
     * @param value value to set the  MeterVendor
     */
    public void setMeterVendor(String value) {
        setAttributeInternal(METERVENDOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterModel.
     * @return the MeterModel
     */
    public String getMeterModel() {
        return (String) getAttributeInternal(METERMODEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterModel.
     * @param value value to set the  MeterModel
     */
    public void setMeterModel(String value) {
        setAttributeInternal(METERMODEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CapColor.
     * @return the CapColor
     */
    public String getCapColor() {
        return (String) getAttributeInternal(CAPCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CapColor.
     * @param value value to set the  CapColor
     */
    public void setCapColor(String value) {
        setAttributeInternal(CAPCOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CapColorDesc.
     * @return the CapColorDesc
     */
    public String getCapColorDesc() {
        return (String) getAttributeInternal(CAPCOLORDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CapColorDesc.
     * @param value value to set the  CapColorDesc
     */
    public void setCapColorDesc(String value) {
        setAttributeInternal(CAPCOLORDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PcoBeat.
     * @return the PcoBeat
     */
    public String getPcoBeat() {
        return (String) getAttributeInternal(PCOBEAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PcoBeat.
     * @param value value to set the  PcoBeat
     */
    public void setPcoBeat(String value) {
        setAttributeInternal(PCOBEAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OldRateArea.
     * @return the OldRateArea
     */
    public String getOldRateArea() {
        return (String) getAttributeInternal(OLDRATEAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OldRateArea.
     * @param value value to set the  OldRateArea
     */
    public void setOldRateArea(String value) {
        setAttributeInternal(OLDRATEAREA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetId.
     * @return the StreetId
     */
    public Number getStreetId() {
        return (Number) getAttributeInternal(STREETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetId.
     * @param value value to set the  StreetId
     */
    public void setStreetId(Number value) {
        setAttributeInternal(STREETID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetName.
     * @return the StreetName
     */
    public String getStreetName() {
        return (String) getAttributeInternal(STREETNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetName.
     * @param value value to set the  StreetName
     */
    public void setStreetName(String value) {
        setAttributeInternal(STREETNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetNum.
     * @return the StreetNum
     */
    public Number getStreetNum() {
        return (Number) getAttributeInternal(STREETNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetNum.
     * @param value value to set the  StreetNum
     */
    public void setStreetNum(Number value) {
        setAttributeInternal(STREETNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetBlock.
     * @return the StreetBlock
     */
    public String getStreetBlock() {
        return (String) getAttributeInternal(STREETBLOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetBlock.
     * @param value value to set the  StreetBlock
     */
    public void setStreetBlock(String value) {
        setAttributeInternal(STREETBLOCK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParityDigitPosition.
     * @return the ParityDigitPosition
     */
    public String getParityDigitPosition() {
        return (String) getAttributeInternal(PARITYDIGITPOSITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParityDigitPosition.
     * @param value value to set the  ParityDigitPosition
     */
    public void setParityDigitPosition(String value) {
        setAttributeInternal(PARITYDIGITPOSITION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetSegCtrlnId.
     * @return the StreetSegCtrlnId
     */
    public Number getStreetSegCtrlnId() {
        return (Number) getAttributeInternal(STREETSEGCTRLNID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetSegCtrlnId.
     * @param value value to set the  StreetSegCtrlnId
     */
    public void setStreetSegCtrlnId(Number value) {
        setAttributeInternal(STREETSEGCTRLNID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Orientation.
     * @return the Orientation
     */
    public Number getOrientation() {
        return (Number) getAttributeInternal(ORIENTATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Orientation.
     * @param value value to set the  Orientation
     */
    public void setOrientation(Number value) {
        setAttributeInternal(ORIENTATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Longitude.
     * @return the Longitude
     */
    public Number getLongitude() {
        return (Number) getAttributeInternal(LONGITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Longitude.
     * @param value value to set the  Longitude
     */
    public void setLongitude(Number value) {
        setAttributeInternal(LONGITUDE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Latitude.
     * @return the Latitude
     */
    public Number getLatitude() {
        return (Number) getAttributeInternal(LATITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Latitude.
     * @param value value to set the  Latitude
     */
    public void setLatitude(Number value) {
        setAttributeInternal(LATITUDE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Geom.
     * @return the Geom
     */
    public SdoGeometry getGeom() {
        return (SdoGeometry)getAttributeInternal(GEOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Geom.
     * @param value value to set the  Geom
     */
    public void setGeom(SdoGeometry value) {
        setAttributeInternal(GEOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegislationRef.
     * @return the LegislationRef
     */
    public String getLegislationRef() {
        return (String) getAttributeInternal(LEGISLATIONREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegislationRef.
     * @param value value to set the  LegislationRef
     */
    public void setLegislationRef(String value) {
        setAttributeInternal(LEGISLATIONREF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegislationDt.
     * @return the LegislationDt
     */
    public Date getLegislationDt() {
        return (Date) getAttributeInternal(LEGISLATIONDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegislationDt.
     * @param value value to set the  LegislationDt
     */
    public void setLegislationDt(Date value) {
        setAttributeInternal(LEGISLATIONDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WorkOrder.
     * @return the WorkOrder
     */
    public String getWorkOrder() {
        return (String) getAttributeInternal(WORKORDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WorkOrder.
     * @param value value to set the  WorkOrder
     */
    public void setWorkOrder(String value) {
        setAttributeInternal(WORKORDER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Comments.
     * @param value value to set the  Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedDt.
     * @return the CreatedDt
     */
    public Date getCreatedDt() {
        return (Date) getAttributeInternal(CREATEDDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedDt.
     * @param value value to set the  CreatedDt
     */
    public void setCreatedDt(Date value) {
        setAttributeInternal(CREATEDDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdDt.
     * @return the LastUpdDt
     */
    public Date getLastUpdDt() {
        return (Date) getAttributeInternal(LASTUPDDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdDt.
     * @param value value to set the  LastUpdDt
     */
    public void setLastUpdDt(Date value) {
        setAttributeInternal(LASTUPDDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdUser.
     * @return the LastUpdUser
     */
    public String getLastUpdUser() {
        return (String) getAttributeInternal(LASTUPDUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdUser.
     * @param value value to set the  LastUpdUser
     */
    public void setLastUpdUser(String value) {
        setAttributeInternal(LASTUPDUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdPgm.
     * @return the LastUpdPgm
     */
    public String getLastUpdPgm() {
        return (String) getAttributeInternal(LASTUPDPGM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdPgm.
     * @param value value to set the  LastUpdPgm
     */
    public void setLastUpdPgm(String value) {
        setAttributeInternal(LASTUPDPGM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CollectionRoute.
     * @return the CollectionRoute
     */
    public String getCollectionRoute() {
        return (String) getAttributeInternal(COLLECTIONROUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CollectionRoute.
     * @param value value to set the  CollectionRoute
     */
    public void setCollectionRoute(String value) {
        setAttributeInternal(COLLECTIONROUTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CollectionSubroute.
     * @return the CollectionSubroute
     */
    public String getCollectionSubroute() {
        return (String) getAttributeInternal(COLLECTIONSUBROUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CollectionSubroute.
     * @param value value to set the  CollectionSubroute
     */
    public void setCollectionSubroute(String value) {
        setAttributeInternal(COLLECTIONSUBROUTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmrRoute.
     * @return the PmrRoute
     */
    public String getPmrRoute() {
        return (String) getAttributeInternal(PMRROUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmrRoute.
     * @param value value to set the  PmrRoute
     */
    public void setPmrRoute(String value) {
        setAttributeInternal(PMRROUTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BlockNum.
     * @return the BlockNum
     */
    public Number getBlockNum() {
        return (Number) getAttributeInternal(BLOCKNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockNum.
     * @param value value to set the  BlockNum
     */
    public void setBlockNum(Number value) {
        setAttributeInternal(BLOCKNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedParkingSpaceRow.
     * @return the SelectedParkingSpaceRow
     */
    public Boolean getSelectedParkingSpaceRow() {
        return (Boolean) getAttributeInternal(SELECTEDPARKINGSPACEROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedParkingSpaceRow.
     * @param value value to set the  SelectedParkingSpaceRow
     */
    public void setSelectedParkingSpaceRow(Boolean value) {
        setAttributeInternal(SELECTEDPARKINGSPACEROW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_MsPayStationIdLovVO.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_MsPayStationIdLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_MSPAYSTATIONIDLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_MsSpaceNumLovVO.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_MsSpaceNumLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_MSSPACENUMLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_SensorFlagLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_SensorFlagLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_SENSORFLAGLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_JurisdictionLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_JurisdictionLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_JURISDICTIONLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_ONOFFSTREETTYPELOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_PmDistrictsLovVO.
     */
    public RowSet getGroupsCommonAM_PmDistrictsLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PMDISTRICTSLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_ACTIVEMETERFLAGLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_SmartMeterFlagLovVO.
     */
    public RowSet getGroupsCommonAM_MeterModels_SmartMeterFlagLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_SMARTMETERFLAGLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_MeterTypeLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_MeterTypeLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_METERTYPELOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_MeterVendorLovVO.
     */
    public RowSet getGroupsCommonAM_MeterModels_MeterVendorLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_METERVENDORLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_MeterModelLovVO.
     */
    public RowSet getGroupsCommonAM_MeterModels_MeterModelLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_METERMODELLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_CapColorLovVO.
     */
    public RowSet getGroupsCommonAM_AllowedValues_CapColorLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_CAPCOLORLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_OLDRATEAREALOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_STREETBLOCKLOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_OspInventory_OspIdFacilityNameLovVO.
     */
    public RowSet getGroupsCommonAM_OspInventory_OspIdFacilityNameLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_OSPINVENTORY_OSPIDFACILITYNAMELOVVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_PCOBEATLOVVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
