package model.bulkeditgroups.views;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 09 11:56:06 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParkingSpaceGroupsUpdtVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CreatedDt {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getCreatedDt();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setCreatedDt((Timestamp)value);
            }
        }
        ,
        LastUpdDt {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getLastUpdDt();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setLastUpdDt((Timestamp)value);
            }
        }
        ,
        LastUpdPgm {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getLastUpdPgm();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setLastUpdPgm((String)value);
            }
        }
        ,
        LastUpdUser {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getLastUpdUser();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setLastUpdUser((String)value);
            }
        }
        ,
        ParkingSpaceId {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getParkingSpaceId();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setParkingSpaceId((Number)value);
            }
        }
        ,
        PsGroupId {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getPsGroupId();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setPsGroupId((Number)value);
            }
        }
        ,
        SelectedParkingSpaceGroupRow {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getSelectedParkingSpaceGroupRow();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setSelectedParkingSpaceGroupRow((Boolean)value);
            }
        }
        ,
        CapColor {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getCapColor();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setCapColor((String)value);
            }
        }
        ,
        PostId {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getPostId();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setPostId((String)value);
            }
        }
        ,
        MsPayStationId {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getMsPayStationId();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setMsPayStationId((String)value);
            }
        }
        ,
        ParkingSpaceId1 {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getParkingSpaceId1();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setParkingSpaceId1((Number)value);
            }
        }
        ,
        ParkingSpaceInventoryUpdtVO {
            public Object get(ParkingSpaceGroupsUpdtVORowImpl obj) {
                return obj.getParkingSpaceInventoryUpdtVO();
            }

            public void put(ParkingSpaceGroupsUpdtVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ParkingSpaceGroupsUpdtVORowImpl object);

        public abstract void put(ParkingSpaceGroupsUpdtVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CREATEDDT = AttributesEnum.CreatedDt.index();
    public static final int LASTUPDDT = AttributesEnum.LastUpdDt.index();
    public static final int LASTUPDPGM = AttributesEnum.LastUpdPgm.index();
    public static final int LASTUPDUSER = AttributesEnum.LastUpdUser.index();
    public static final int PARKINGSPACEID = AttributesEnum.ParkingSpaceId.index();
    public static final int PSGROUPID = AttributesEnum.PsGroupId.index();
    public static final int SELECTEDPARKINGSPACEGROUPROW = AttributesEnum.SelectedParkingSpaceGroupRow.index();
    public static final int CAPCOLOR = AttributesEnum.CapColor.index();
    public static final int POSTID = AttributesEnum.PostId.index();
    public static final int MSPAYSTATIONID = AttributesEnum.MsPayStationId.index();
    public static final int PARKINGSPACEID1 = AttributesEnum.ParkingSpaceId1.index();
    public static final int PARKINGSPACEINVENTORYUPDTVO = AttributesEnum.ParkingSpaceInventoryUpdtVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ParkingSpaceGroupsUpdtVORowImpl() {
    }

    /**
     * Gets ParkingSpaceGroupsEO entity object.
     * @return the ParkingSpaceGroupsEO
     */
    public EntityImpl getParkingSpaceGroupsEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets ParkingSpaceInventoryEO entity object.
     * @return the ParkingSpaceInventoryEO
     */
    public EntityImpl getParkingSpaceInventoryEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for CREATED_DT using the alias name CreatedDt.
     * @return the CREATED_DT
     */
    public Timestamp getCreatedDt() {
        return (Timestamp) getAttributeInternal(CREATEDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DT using the alias name CreatedDt.
     * @param value value to set the CREATED_DT
     */
    public void setCreatedDt(Timestamp value) {
        setAttributeInternal(CREATEDDT, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_DT using the alias name LastUpdDt.
     * @return the LAST_UPD_DT
     */
    public Timestamp getLastUpdDt() {
        return (Timestamp) getAttributeInternal(LASTUPDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_DT using the alias name LastUpdDt.
     * @param value value to set the LAST_UPD_DT
     */
    public void setLastUpdDt(Timestamp value) {
        setAttributeInternal(LASTUPDDT, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_PGM using the alias name LastUpdPgm.
     * @return the LAST_UPD_PGM
     */
    public String getLastUpdPgm() {
        return (String) getAttributeInternal(LASTUPDPGM);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_PGM using the alias name LastUpdPgm.
     * @param value value to set the LAST_UPD_PGM
     */
    public void setLastUpdPgm(String value) {
        setAttributeInternal(LASTUPDPGM, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_USER using the alias name LastUpdUser.
     * @return the LAST_UPD_USER
     */
    public String getLastUpdUser() {
        return (String) getAttributeInternal(LASTUPDUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_USER using the alias name LastUpdUser.
     * @param value value to set the LAST_UPD_USER
     */
    public void setLastUpdUser(String value) {
        setAttributeInternal(LASTUPDUSER, value);
    }

    /**
     * Gets the attribute value for PARKING_SPACE_ID using the alias name ParkingSpaceId.
     * @return the PARKING_SPACE_ID
     */
    public Number getParkingSpaceId() {
        return (Number) getAttributeInternal(PARKINGSPACEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARKING_SPACE_ID using the alias name ParkingSpaceId.
     * @param value value to set the PARKING_SPACE_ID
     */
    public void setParkingSpaceId(Number value) {
        setAttributeInternal(PARKINGSPACEID, value);
    }

    /**
     * Gets the attribute value for PS_GROUP_ID using the alias name PsGroupId.
     * @return the PS_GROUP_ID
     */
    public Number getPsGroupId() {
        return (Number) getAttributeInternal(PSGROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for PS_GROUP_ID using the alias name PsGroupId.
     * @param value value to set the PS_GROUP_ID
     */
    public void setPsGroupId(Number value) {
        setAttributeInternal(PSGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedParkingSpaceGroupRow.
     * @return the SelectedParkingSpaceGroupRow
     */
    public Boolean getSelectedParkingSpaceGroupRow() {
        return (Boolean) getAttributeInternal(SELECTEDPARKINGSPACEGROUPROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedParkingSpaceGroupRow.
     * @param value value to set the  SelectedParkingSpaceGroupRow
     */
    public void setSelectedParkingSpaceGroupRow(Boolean value) {
        setAttributeInternal(SELECTEDPARKINGSPACEGROUPROW, value);
    }

    /**
     * Gets the attribute value for CAP_COLOR using the alias name CapColor.
     * @return the CAP_COLOR
     */
    public String getCapColor() {
        return (String) getAttributeInternal(CAPCOLOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CAP_COLOR using the alias name CapColor.
     * @param value value to set the CAP_COLOR
     */
    public void setCapColor(String value) {
        setAttributeInternal(CAPCOLOR, value);
    }


    /**
     * Gets the attribute value for POST_ID using the alias name PostId.
     * @return the POST_ID
     */
    public String getPostId() {
        return (String) getAttributeInternal(POSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_ID using the alias name PostId.
     * @param value value to set the POST_ID
     */
    public void setPostId(String value) {
        setAttributeInternal(POSTID, value);
    }

    /**
     * Gets the attribute value for MS_PAY_STATION_ID using the alias name MsPayStationId.
     * @return the MS_PAY_STATION_ID
     */
    public String getMsPayStationId() {
        return (String) getAttributeInternal(MSPAYSTATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for MS_PAY_STATION_ID using the alias name MsPayStationId.
     * @param value value to set the MS_PAY_STATION_ID
     */
    public void setMsPayStationId(String value) {
        setAttributeInternal(MSPAYSTATIONID, value);
    }

    /**
     * Gets the attribute value for PARKING_SPACE_ID using the alias name ParkingSpaceId1.
     * @return the PARKING_SPACE_ID
     */
    public Number getParkingSpaceId1() {
        return (Number) getAttributeInternal(PARKINGSPACEID1);
    }

    /**
     * Sets <code>value</code> as attribute value for PARKING_SPACE_ID using the alias name ParkingSpaceId1.
     * @param value value to set the PARKING_SPACE_ID
     */
    public void setParkingSpaceId1(Number value) {
        setAttributeInternal(PARKINGSPACEID1, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ParkingSpaceInventoryUpdtVO.
     */
    public RowIterator getParkingSpaceInventoryUpdtVO() {
        return (RowIterator)getAttributeInternal(PARKINGSPACEINVENTORYUPDTVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
