package model.availableapioverrides.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:08:38 PST 2012
// ---------------------------------------------------------------------
public interface AAOJoinedUpdtVORow extends Row {
    Date getAAOCreatedDt();

    Date getAAOLastUpdDt();

    String getAAOLastUpdPgm();

    String getAAOLastUpdUser();

    Number getId();

    void setAAOCreatedDt(Date value);

    void setAAOLastUpdDt(Date value);

    void setAAOLastUpdPgm(String value);

    void setAAOLastUpdUser(String value);

    void setId(Number value);
}
