package model.availableapioverrides.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:30:31 PST 2012
// ---------------------------------------------------------------------
public interface AvailApiOspInventoryVwRoVORow extends Row {
    Number getOspId();

    void setOspId(Number value);
}
