package model.availableapioverrides.views.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:49:46 PST 2012
// ---------------------------------------------------------------------
public interface AvailApiBlockfacesVwRoVORow extends Row {
    Number getBlockfaceId();

    void setBlockfaceId(Number value);

    Boolean getSelectedBlockface();

    void setSelectedBlockface(Boolean value);
}
