package model.bulkeditgroups.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 10:08:38 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BlocksRoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BlocksRoVOImpl() {
    }
}
