package model.bulkeditgroups.views;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 09 11:55:12 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BlockGroupsUpdtVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BlockId {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getBlockId();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setBlockId((Number)value);
            }
        }
        ,
        CreatedDt {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getCreatedDt();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setCreatedDt((Timestamp)value);
            }
        }
        ,
        GroupId {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getGroupId();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setGroupId((Number)value);
            }
        }
        ,
        LastUpdDt {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getLastUpdDt();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setLastUpdDt((Timestamp)value);
            }
        }
        ,
        LastUpdPgm {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getLastUpdPgm();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setLastUpdPgm((String)value);
            }
        }
        ,
        LastUpdUser {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getLastUpdUser();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setLastUpdUser((String)value);
            }
        }
        ,
        SelectedBlockGroupRow {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getSelectedBlockGroupRow();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setSelectedBlockGroupRow((Boolean)value);
            }
        }
        ,
        StreetName {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getStreetName();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setStreetName((String)value);
            }
        }
        ,
        SdeId {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getSdeId();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setSdeId((Number)value);
            }
        }
        ,
        BlockNum {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getBlockNum();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setBlockNum((Number)value);
            }
        }
        ,
        BLOCK_DESC {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getBLOCK_DESC();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setBLOCK_DESC((String)value);
            }
        }
        ,
        BlocksUpdtVO {
            public Object get(BlockGroupsUpdtVORowImpl obj) {
                return obj.getBlocksUpdtVO();
            }

            public void put(BlockGroupsUpdtVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BlockGroupsUpdtVORowImpl object);

        public abstract void put(BlockGroupsUpdtVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BLOCKID = AttributesEnum.BlockId.index();
    public static final int CREATEDDT = AttributesEnum.CreatedDt.index();
    public static final int GROUPID = AttributesEnum.GroupId.index();
    public static final int LASTUPDDT = AttributesEnum.LastUpdDt.index();
    public static final int LASTUPDPGM = AttributesEnum.LastUpdPgm.index();
    public static final int LASTUPDUSER = AttributesEnum.LastUpdUser.index();
    public static final int SELECTEDBLOCKGROUPROW = AttributesEnum.SelectedBlockGroupRow.index();
    public static final int STREETNAME = AttributesEnum.StreetName.index();
    public static final int SDEID = AttributesEnum.SdeId.index();
    public static final int BLOCKNUM = AttributesEnum.BlockNum.index();
    public static final int BLOCK_DESC = AttributesEnum.BLOCK_DESC.index();
    public static final int BLOCKSUPDTVO = AttributesEnum.BlocksUpdtVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BlockGroupsUpdtVORowImpl() {
    }

    /**
     * Gets BlockGroupsEO entity object.
     * @return the BlockGroupsEO
     */
    public EntityImpl getBlockGroupsEO() {
        return (EntityImpl)getEntity(0);
    }


    /**
     * Gets BlocksEO entity object.
     * @return the BlocksEO
     */
    public EntityImpl getBlocksEO() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for BLOCK_ID using the alias name BlockId.
     * @return the BLOCK_ID
     */
    public Number getBlockId() {
        return (Number) getAttributeInternal(BLOCKID);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOCK_ID using the alias name BlockId.
     * @param value value to set the BLOCK_ID
     */
    public void setBlockId(Number value) {
        setAttributeInternal(BLOCKID, value);
    }

    /**
     * Gets the attribute value for CREATED_DT using the alias name CreatedDt.
     * @return the CREATED_DT
     */
    public Timestamp getCreatedDt() {
        return (Timestamp) getAttributeInternal(CREATEDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DT using the alias name CreatedDt.
     * @param value value to set the CREATED_DT
     */
    public void setCreatedDt(Timestamp value) {
        setAttributeInternal(CREATEDDT, value);
    }

    /**
     * Gets the attribute value for GROUP_ID using the alias name GroupId.
     * @return the GROUP_ID
     */
    public Number getGroupId() {
        return (Number) getAttributeInternal(GROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_ID using the alias name GroupId.
     * @param value value to set the GROUP_ID
     */
    public void setGroupId(Number value) {
        setAttributeInternal(GROUPID, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_DT using the alias name LastUpdDt.
     * @return the LAST_UPD_DT
     */
    public Timestamp getLastUpdDt() {
        return (Timestamp) getAttributeInternal(LASTUPDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_DT using the alias name LastUpdDt.
     * @param value value to set the LAST_UPD_DT
     */
    public void setLastUpdDt(Timestamp value) {
        setAttributeInternal(LASTUPDDT, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_PGM using the alias name LastUpdPgm.
     * @return the LAST_UPD_PGM
     */
    public String getLastUpdPgm() {
        return (String) getAttributeInternal(LASTUPDPGM);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_PGM using the alias name LastUpdPgm.
     * @param value value to set the LAST_UPD_PGM
     */
    public void setLastUpdPgm(String value) {
        setAttributeInternal(LASTUPDPGM, value);
    }

    /**
     * Gets the attribute value for LAST_UPD_USER using the alias name LastUpdUser.
     * @return the LAST_UPD_USER
     */
    public String getLastUpdUser() {
        return (String) getAttributeInternal(LASTUPDUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPD_USER using the alias name LastUpdUser.
     * @param value value to set the LAST_UPD_USER
     */
    public void setLastUpdUser(String value) {
        setAttributeInternal(LASTUPDUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedBlockGroupRow.
     * @return the SelectedBlockGroupRow
     */
    public Boolean getSelectedBlockGroupRow() {
        return (Boolean) getAttributeInternal(SELECTEDBLOCKGROUPROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedBlockGroupRow.
     * @param value value to set the  SelectedBlockGroupRow
     */
    public void setSelectedBlockGroupRow(Boolean value) {
        setAttributeInternal(SELECTEDBLOCKGROUPROW, value);
    }


    /**
     * Gets the attribute value for STREET_NAME using the alias name StreetName.
     * @return the STREET_NAME
     */
    public String getStreetName() {
        return (String) getAttributeInternal(STREETNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for STREET_NAME using the alias name StreetName.
     * @param value value to set the STREET_NAME
     */
    public void setStreetName(String value) {
        setAttributeInternal(STREETNAME, value);
    }

    /**
     * Gets the attribute value for SDE_ID using the alias name SdeId.
     * @return the SDE_ID
     */
    public Number getSdeId() {
        return (Number) getAttributeInternal(SDEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SDE_ID using the alias name SdeId.
     * @param value value to set the SDE_ID
     */
    public void setSdeId(Number value) {
        setAttributeInternal(SDEID, value);
    }

    /**
     * Gets the attribute value for BLOCK_NUM using the alias name BlockNum.
     * @return the BLOCK_NUM
     */
    public Number getBlockNum() {
        return (Number) getAttributeInternal(BLOCKNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for BLOCK_NUM using the alias name BlockNum.
     * @param value value to set the BLOCK_NUM
     */
    public void setBlockNum(Number value) {
        setAttributeInternal(BLOCKNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BLOCK_DESC.
     * @return the BLOCK_DESC
     */
    public String getBLOCK_DESC() {
        return (String) getAttributeInternal(BLOCK_DESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BLOCK_DESC.
     * @param value value to set the  BLOCK_DESC
     */
    public void setBLOCK_DESC(String value) {
        setAttributeInternal(BLOCK_DESC, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BlocksUpdtVO.
     */
    public RowIterator getBlocksUpdtVO() {
        return (RowIterator)getAttributeInternal(BLOCKSUPDTVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
