package model.bulkeditgroups.views;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 18:48:52 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MeterRateScheduleRoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        MeterRateSchedId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getMeterRateSchedId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setMeterRateSchedId((Number)value);
            }
        }
        ,
        ParkingSpaceId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getParkingSpaceId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setParkingSpaceId((Number)value);
            }
        }
        ,
        RateType {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getRateType();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setRateType((String)value);
            }
        }
        ,
        Ratetypedesc {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getRatetypedesc();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setRatetypedesc((String)value);
            }
        }
        ,
        RateStatus {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getRateStatus();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setRateStatus((String)value);
            }
        }
        ,
        Ratestatusdesc {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getRatestatusdesc();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setRatestatusdesc((String)value);
            }
        }
        ,
        Rate {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getRate();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setRate((Number)value);
            }
        }
        ,
        RateChgRef {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getRateChgRef();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setRateChgRef((String)value);
            }
        }
        ,
        EventId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getEventId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setEventId((Number)value);
            }
        }
        ,
        SchedPriority {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getSchedPriority();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setSchedPriority((Number)value);
            }
        }
        ,
        EffFromDt {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getEffFromDt();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setEffFromDt((Date)value);
            }
        }
        ,
        EffToDt {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getEffToDt();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setEffToDt((Date)value);
            }
        }
        ,
        PsGroupId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getPsGroupId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setPsGroupId((Number)value);
            }
        }
        ,
        FromTime {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getFromTime();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setFromTime((Number)value);
            }
        }
        ,
        ToTime {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getToTime();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setToTime((Number)value);
            }
        }
        ,
        DaysApplied {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getDaysApplied();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setDaysApplied((String)value);
            }
        }
        ,
        PostId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getPostId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setPostId((String)value);
            }
        }
        ,
        MsPayStationId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getMsPayStationId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setMsPayStationId((String)value);
            }
        }
        ,
        MsSpaceNum {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getMsSpaceNum();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setMsSpaceNum((Number)value);
            }
        }
        ,
        SensorFlag {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getSensorFlag();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setSensorFlag((String)value);
            }
        }
        ,
        OnOffstreetType {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getOnOffstreetType();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setOnOffstreetType((String)value);
            }
        }
        ,
        Jurisdiction {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getJurisdiction();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setJurisdiction((String)value);
            }
        }
        ,
        PmDistrictName {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getPmDistrictName();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setPmDistrictName((String)value);
            }
        }
        ,
        BlockfaceId {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getBlockfaceId();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setBlockfaceId((Number)value);
            }
        }
        ,
        ActiveMeterFlag {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getActiveMeterFlag();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setActiveMeterFlag((String)value);
            }
        }
        ,
        SmartMeterFlag {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getSmartMeterFlag();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setSmartMeterFlag((String)value);
            }
        }
        ,
        MeterType {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getMeterType();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setMeterType((String)value);
            }
        }
        ,
        MeterVendor {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getMeterVendor();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setMeterVendor((String)value);
            }
        }
        ,
        MeterModel {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getMeterModel();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setMeterModel((String)value);
            }
        }
        ,
        CapColor {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getCapColor();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setCapColor((String)value);
            }
        }
        ,
        PcoBeat {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getPcoBeat();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setPcoBeat((String)value);
            }
        }
        ,
        OldRateArea {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getOldRateArea();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setOldRateArea((String)value);
            }
        }
        ,
        StreetBlock {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getStreetBlock();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setStreetBlock((String)value);
            }
        }
        ,
        SelectedMeterRateScheduleRow {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getSelectedMeterRateScheduleRow();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setSelectedMeterRateScheduleRow((Boolean)value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_RateTypeLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_RateTypeLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_RateStatusLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_RateStatusLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterRateSched_SchedPriorityLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterRateSched_SchedPriorityLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterRateSched_FromTimeLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterRateSched_FromTimeLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterOpSched_ToTimeLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterOpSched_ToTimeLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterRateSched_DaysAppliedLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterRateSched_DaysAppliedLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_SensorFlagLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_SensorFlagLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_PmDistrictsLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_PmDistrictsLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_SmartMeterFlagLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_SmartMeterFlagLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_MeterTypeLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_MeterTypeLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_MeterVendorLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_MeterVendorLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_MeterModels_MeterModelLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_MeterModels_MeterModelLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_CapColorLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_CapColorLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GroupsCommonAM_AllowedValues_JurisdictionLovVO1 {
            public Object get(MeterRateScheduleRoVORowImpl obj) {
                return obj.getGroupsCommonAM_AllowedValues_JurisdictionLovVO1();
            }

            public void put(MeterRateScheduleRoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MeterRateScheduleRoVORowImpl object);

        public abstract void put(MeterRateScheduleRoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int METERRATESCHEDID = AttributesEnum.MeterRateSchedId.index();
    public static final int PARKINGSPACEID = AttributesEnum.ParkingSpaceId.index();
    public static final int RATETYPE = AttributesEnum.RateType.index();
    public static final int RATETYPEDESC = AttributesEnum.Ratetypedesc.index();
    public static final int RATESTATUS = AttributesEnum.RateStatus.index();
    public static final int RATESTATUSDESC = AttributesEnum.Ratestatusdesc.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int RATECHGREF = AttributesEnum.RateChgRef.index();
    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int SCHEDPRIORITY = AttributesEnum.SchedPriority.index();
    public static final int EFFFROMDT = AttributesEnum.EffFromDt.index();
    public static final int EFFTODT = AttributesEnum.EffToDt.index();
    public static final int PSGROUPID = AttributesEnum.PsGroupId.index();
    public static final int FROMTIME = AttributesEnum.FromTime.index();
    public static final int TOTIME = AttributesEnum.ToTime.index();
    public static final int DAYSAPPLIED = AttributesEnum.DaysApplied.index();
    public static final int POSTID = AttributesEnum.PostId.index();
    public static final int MSPAYSTATIONID = AttributesEnum.MsPayStationId.index();
    public static final int MSSPACENUM = AttributesEnum.MsSpaceNum.index();
    public static final int SENSORFLAG = AttributesEnum.SensorFlag.index();
    public static final int ONOFFSTREETTYPE = AttributesEnum.OnOffstreetType.index();
    public static final int JURISDICTION = AttributesEnum.Jurisdiction.index();
    public static final int PMDISTRICTNAME = AttributesEnum.PmDistrictName.index();
    public static final int BLOCKFACEID = AttributesEnum.BlockfaceId.index();
    public static final int ACTIVEMETERFLAG = AttributesEnum.ActiveMeterFlag.index();
    public static final int SMARTMETERFLAG = AttributesEnum.SmartMeterFlag.index();
    public static final int METERTYPE = AttributesEnum.MeterType.index();
    public static final int METERVENDOR = AttributesEnum.MeterVendor.index();
    public static final int METERMODEL = AttributesEnum.MeterModel.index();
    public static final int CAPCOLOR = AttributesEnum.CapColor.index();
    public static final int PCOBEAT = AttributesEnum.PcoBeat.index();
    public static final int OLDRATEAREA = AttributesEnum.OldRateArea.index();
    public static final int STREETBLOCK = AttributesEnum.StreetBlock.index();
    public static final int SELECTEDMETERRATESCHEDULEROW = AttributesEnum.SelectedMeterRateScheduleRow.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_RATETYPELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_RateTypeLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_RATESTATUSLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_RateStatusLovVO1.index();
    public static final int GROUPSCOMMONAM_METERRATESCHED_SCHEDPRIORITYLOVVO1 = AttributesEnum.GroupsCommonAM_MeterRateSched_SchedPriorityLovVO1.index();
    public static final int GROUPSCOMMONAM_METERRATESCHED_FROMTIMELOVVO1 = AttributesEnum.GroupsCommonAM_MeterRateSched_FromTimeLovVO1.index();
    public static final int GROUPSCOMMONAM_METEROPSCHED_TOTIMELOVVO1 = AttributesEnum.GroupsCommonAM_MeterOpSched_ToTimeLovVO1.index();
    public static final int GROUPSCOMMONAM_METERRATESCHED_DAYSAPPLIEDLOVVO1 = AttributesEnum.GroupsCommonAM_MeterRateSched_DaysAppliedLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_SENSORFLAGLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_SensorFlagLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_ONOFFSTREETTYPELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1.index();
    public static final int GROUPSCOMMONAM_PMDISTRICTSLOVVO1 = AttributesEnum.GroupsCommonAM_PmDistrictsLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_ACTIVEMETERFLAGLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1.index();
    public static final int GROUPSCOMMONAM_METERMODELS_SMARTMETERFLAGLOVVO1 = AttributesEnum.GroupsCommonAM_MeterModels_SmartMeterFlagLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_METERTYPELOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_MeterTypeLovVO1.index();
    public static final int GROUPSCOMMONAM_METERMODELS_METERVENDORLOVVO1 = AttributesEnum.GroupsCommonAM_MeterModels_MeterVendorLovVO1.index();
    public static final int GROUPSCOMMONAM_METERMODELS_METERMODELLOVVO1 = AttributesEnum.GroupsCommonAM_MeterModels_MeterModelLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_CAPCOLORLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_CapColorLovVO1.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_PCOBEATLOVVO1 = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_OLDRATEAREALOVVO1 = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1.index();
    public static final int GROUPSCOMMONAM_PARKINGSPACEINVENTORY_STREETBLOCKLOVVO1 = AttributesEnum.GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1.index();
    public static final int GROUPSCOMMONAM_ALLOWEDVALUES_JURISDICTIONLOVVO1 = AttributesEnum.GroupsCommonAM_AllowedValues_JurisdictionLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MeterRateScheduleRoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute MeterRateSchedId.
     * @return the MeterRateSchedId
     */
    public Number getMeterRateSchedId() {
        return (Number) getAttributeInternal(METERRATESCHEDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterRateSchedId.
     * @param value value to set the  MeterRateSchedId
     */
    public void setMeterRateSchedId(Number value) {
        setAttributeInternal(METERRATESCHEDID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParkingSpaceId.
     * @return the ParkingSpaceId
     */
    public Number getParkingSpaceId() {
        return (Number) getAttributeInternal(PARKINGSPACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParkingSpaceId.
     * @param value value to set the  ParkingSpaceId
     */
    public void setParkingSpaceId(Number value) {
        setAttributeInternal(PARKINGSPACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RateType.
     * @return the RateType
     */
    public String getRateType() {
        return (String) getAttributeInternal(RATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RateType.
     * @param value value to set the  RateType
     */
    public void setRateType(String value) {
        setAttributeInternal(RATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Ratetypedesc.
     * @return the Ratetypedesc
     */
    public String getRatetypedesc() {
        return (String) getAttributeInternal(RATETYPEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Ratetypedesc.
     * @param value value to set the  Ratetypedesc
     */
    public void setRatetypedesc(String value) {
        setAttributeInternal(RATETYPEDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RateStatus.
     * @return the RateStatus
     */
    public String getRateStatus() {
        return (String) getAttributeInternal(RATESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RateStatus.
     * @param value value to set the  RateStatus
     */
    public void setRateStatus(String value) {
        setAttributeInternal(RATESTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Ratestatusdesc.
     * @return the Ratestatusdesc
     */
    public String getRatestatusdesc() {
        return (String) getAttributeInternal(RATESTATUSDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Ratestatusdesc.
     * @param value value to set the  Ratestatusdesc
     */
    public void setRatestatusdesc(String value) {
        setAttributeInternal(RATESTATUSDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Rate.
     * @return the Rate
     */
    public Number getRate() {
        return (Number) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Rate.
     * @param value value to set the  Rate
     */
    public void setRate(Number value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RateChgRef.
     * @return the RateChgRef
     */
    public String getRateChgRef() {
        return (String) getAttributeInternal(RATECHGREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RateChgRef.
     * @param value value to set the  RateChgRef
     */
    public void setRateChgRef(String value) {
        setAttributeInternal(RATECHGREF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EventId.
     * @return the EventId
     */
    public Number getEventId() {
        return (Number) getAttributeInternal(EVENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EventId.
     * @param value value to set the  EventId
     */
    public void setEventId(Number value) {
        setAttributeInternal(EVENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SchedPriority.
     * @return the SchedPriority
     */
    public Number getSchedPriority() {
        return (Number) getAttributeInternal(SCHEDPRIORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SchedPriority.
     * @param value value to set the  SchedPriority
     */
    public void setSchedPriority(Number value) {
        setAttributeInternal(SCHEDPRIORITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffFromDt.
     * @return the EffFromDt
     */
    public Date getEffFromDt() {
        return (Date) getAttributeInternal(EFFFROMDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffFromDt.
     * @param value value to set the  EffFromDt
     */
    public void setEffFromDt(Date value) {
        setAttributeInternal(EFFFROMDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EffToDt.
     * @return the EffToDt
     */
    public Date getEffToDt() {
        return (Date) getAttributeInternal(EFFTODT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EffToDt.
     * @param value value to set the  EffToDt
     */
    public void setEffToDt(Date value) {
        setAttributeInternal(EFFTODT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PsGroupId.
     * @return the PsGroupId
     */
    public Number getPsGroupId() {
        return (Number) getAttributeInternal(PSGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PsGroupId.
     * @param value value to set the  PsGroupId
     */
    public void setPsGroupId(Number value) {
        setAttributeInternal(PSGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FromTime.
     * @return the FromTime
     */
    public Number getFromTime() {
        return (Number) getAttributeInternal(FROMTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FromTime.
     * @param value value to set the  FromTime
     */
    public void setFromTime(Number value) {
        setAttributeInternal(FROMTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ToTime.
     * @return the ToTime
     */
    public Number getToTime() {
        return (Number) getAttributeInternal(TOTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ToTime.
     * @param value value to set the  ToTime
     */
    public void setToTime(Number value) {
        setAttributeInternal(TOTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DaysApplied.
     * @return the DaysApplied
     */
    public String getDaysApplied() {
        return (String) getAttributeInternal(DAYSAPPLIED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DaysApplied.
     * @param value value to set the  DaysApplied
     */
    public void setDaysApplied(String value) {
        setAttributeInternal(DAYSAPPLIED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PostId.
     * @return the PostId
     */
    public String getPostId() {
        return (String) getAttributeInternal(POSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PostId.
     * @param value value to set the  PostId
     */
    public void setPostId(String value) {
        setAttributeInternal(POSTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsPayStationId.
     * @return the MsPayStationId
     */
    public String getMsPayStationId() {
        return (String) getAttributeInternal(MSPAYSTATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsPayStationId.
     * @param value value to set the  MsPayStationId
     */
    public void setMsPayStationId(String value) {
        setAttributeInternal(MSPAYSTATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MsSpaceNum.
     * @return the MsSpaceNum
     */
    public Number getMsSpaceNum() {
        return (Number) getAttributeInternal(MSSPACENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MsSpaceNum.
     * @param value value to set the  MsSpaceNum
     */
    public void setMsSpaceNum(Number value) {
        setAttributeInternal(MSSPACENUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SensorFlag.
     * @return the SensorFlag
     */
    public String getSensorFlag() {
        return (String) getAttributeInternal(SENSORFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SensorFlag.
     * @param value value to set the  SensorFlag
     */
    public void setSensorFlag(String value) {
        setAttributeInternal(SENSORFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OnOffstreetType.
     * @return the OnOffstreetType
     */
    public String getOnOffstreetType() {
        return (String) getAttributeInternal(ONOFFSTREETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OnOffstreetType.
     * @param value value to set the  OnOffstreetType
     */
    public void setOnOffstreetType(String value) {
        setAttributeInternal(ONOFFSTREETTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Jurisdiction.
     * @return the Jurisdiction
     */
    public String getJurisdiction() {
        return (String) getAttributeInternal(JURISDICTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Jurisdiction.
     * @param value value to set the  Jurisdiction
     */
    public void setJurisdiction(String value) {
        setAttributeInternal(JURISDICTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PmDistrictName.
     * @return the PmDistrictName
     */
    public String getPmDistrictName() {
        return (String) getAttributeInternal(PMDISTRICTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PmDistrictName.
     * @param value value to set the  PmDistrictName
     */
    public void setPmDistrictName(String value) {
        setAttributeInternal(PMDISTRICTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BlockfaceId.
     * @return the BlockfaceId
     */
    public Number getBlockfaceId() {
        return (Number) getAttributeInternal(BLOCKFACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockfaceId.
     * @param value value to set the  BlockfaceId
     */
    public void setBlockfaceId(Number value) {
        setAttributeInternal(BLOCKFACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveMeterFlag.
     * @return the ActiveMeterFlag
     */
    public String getActiveMeterFlag() {
        return (String) getAttributeInternal(ACTIVEMETERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveMeterFlag.
     * @param value value to set the  ActiveMeterFlag
     */
    public void setActiveMeterFlag(String value) {
        setAttributeInternal(ACTIVEMETERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SmartMeterFlag.
     * @return the SmartMeterFlag
     */
    public String getSmartMeterFlag() {
        return (String) getAttributeInternal(SMARTMETERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SmartMeterFlag.
     * @param value value to set the  SmartMeterFlag
     */
    public void setSmartMeterFlag(String value) {
        setAttributeInternal(SMARTMETERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterType.
     * @return the MeterType
     */
    public String getMeterType() {
        return (String) getAttributeInternal(METERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterType.
     * @param value value to set the  MeterType
     */
    public void setMeterType(String value) {
        setAttributeInternal(METERTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterVendor.
     * @return the MeterVendor
     */
    public String getMeterVendor() {
        return (String) getAttributeInternal(METERVENDOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterVendor.
     * @param value value to set the  MeterVendor
     */
    public void setMeterVendor(String value) {
        setAttributeInternal(METERVENDOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MeterModel.
     * @return the MeterModel
     */
    public String getMeterModel() {
        return (String) getAttributeInternal(METERMODEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MeterModel.
     * @param value value to set the  MeterModel
     */
    public void setMeterModel(String value) {
        setAttributeInternal(METERMODEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CapColor.
     * @return the CapColor
     */
    public String getCapColor() {
        return (String) getAttributeInternal(CAPCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CapColor.
     * @param value value to set the  CapColor
     */
    public void setCapColor(String value) {
        setAttributeInternal(CAPCOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PcoBeat.
     * @return the PcoBeat
     */
    public String getPcoBeat() {
        return (String) getAttributeInternal(PCOBEAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PcoBeat.
     * @param value value to set the  PcoBeat
     */
    public void setPcoBeat(String value) {
        setAttributeInternal(PCOBEAT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OldRateArea.
     * @return the OldRateArea
     */
    public String getOldRateArea() {
        return (String) getAttributeInternal(OLDRATEAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OldRateArea.
     * @param value value to set the  OldRateArea
     */
    public void setOldRateArea(String value) {
        setAttributeInternal(OLDRATEAREA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetBlock.
     * @return the StreetBlock
     */
    public String getStreetBlock() {
        return (String) getAttributeInternal(STREETBLOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetBlock.
     * @param value value to set the  StreetBlock
     */
    public void setStreetBlock(String value) {
        setAttributeInternal(STREETBLOCK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedMeterRateScheduleRow.
     * @return the SelectedMeterRateScheduleRow
     */
    public Boolean getSelectedMeterRateScheduleRow() {
        return (Boolean) getAttributeInternal(SELECTEDMETERRATESCHEDULEROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedMeterRateScheduleRow.
     * @param value value to set the  SelectedMeterRateScheduleRow
     */
    public void setSelectedMeterRateScheduleRow(Boolean value) {
        setAttributeInternal(SELECTEDMETERRATESCHEDULEROW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_RateTypeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_RateTypeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_RATETYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_RateStatusLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_RateStatusLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_RATESTATUSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterRateSched_SchedPriorityLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterRateSched_SchedPriorityLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERRATESCHED_SCHEDPRIORITYLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterRateSched_FromTimeLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterRateSched_FromTimeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERRATESCHED_FROMTIMELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterOpSched_ToTimeLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterOpSched_ToTimeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METEROPSCHED_TOTIMELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterRateSched_DaysAppliedLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterRateSched_DaysAppliedLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERRATESCHED_DAYSAPPLIEDLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_SensorFlagLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_SensorFlagLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_SENSORFLAGLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_OnOffStreetTypeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_ONOFFSTREETTYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_PmDistrictsLovVO1.
     */
    public RowSet getGroupsCommonAM_PmDistrictsLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PMDISTRICTSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_ActiveMeterFlagLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_ACTIVEMETERFLAGLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_SmartMeterFlagLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterModels_SmartMeterFlagLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_SMARTMETERFLAGLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_MeterTypeLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_MeterTypeLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_METERTYPELOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_MeterVendorLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterModels_MeterVendorLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_METERVENDORLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_MeterModels_MeterModelLovVO1.
     */
    public RowSet getGroupsCommonAM_MeterModels_MeterModelLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_METERMODELS_METERMODELLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_CapColorLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_CapColorLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_CAPCOLORLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_PcoBeatLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_PCOBEATLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_OldRateAreaLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_OLDRATEAREALOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1.
     */
    public RowSet getGroupsCommonAM_ParkingSpaceInventory_StreetBlockLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_PARKINGSPACEINVENTORY_STREETBLOCKLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GroupsCommonAM_AllowedValues_JurisdictionLovVO1.
     */
    public RowSet getGroupsCommonAM_AllowedValues_JurisdictionLovVO1() {
        return (RowSet)getAttributeInternal(GROUPSCOMMONAM_ALLOWEDVALUES_JURISDICTIONLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
