package model.availableapioverrides.views.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:08:38 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AAOJoinedUpdtVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AAOJoinedUpdtVORowClient() {
    }

    public Date getAAOCreatedDt() {
        return (Date)getAttribute("AAOCreatedDt");
    }

    public Date getAAOLastUpdDt() {
        return (Date)getAttribute("AAOLastUpdDt");
    }

    public String getAAOLastUpdPgm() {
        return (String)getAttribute("AAOLastUpdPgm");
    }

    public String getAAOLastUpdUser() {
        return (String)getAttribute("AAOLastUpdUser");
    }

    public Number getId() {
        return (Number)getAttribute("Id");
    }

    public void setAAOCreatedDt(Date value) {
        setAttribute("AAOCreatedDt", value);
    }

    public void setAAOLastUpdDt(Date value) {
        setAttribute("AAOLastUpdDt", value);
    }

    public void setAAOLastUpdPgm(String value) {
        setAttribute("AAOLastUpdPgm", value);
    }

    public void setAAOLastUpdUser(String value) {
        setAttribute("AAOLastUpdUser", value);
    }

    public void setId(Number value) {
        setAttribute("Id", value);
    }
}
