package model.availableapioverrides.views.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:49:46 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailApiBlockfacesVwRoVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AvailApiBlockfacesVwRoVORowClient() {
    }

    public Number getBlockfaceId() {
        return (Number)getAttribute("BlockfaceId");
    }

    public void setBlockfaceId(Number value) {
        setAttribute("BlockfaceId", value);
    }

    public Boolean getSelectedBlockface() {
        return (Boolean)getAttribute("SelectedBlockface");
    }

    public void setSelectedBlockface(Boolean value) {
        setAttribute("SelectedBlockface", value);
    }
}
