package model.availableapioverrides.views.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:43:16 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailApiBlocksVwRoVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AvailApiBlocksVwRoVORowClient() {
    }


    public Number getBlockId() {
        return (Number)getAttribute("BlockId");
    }

    public void setBlockId(Number value) {
        setAttribute("BlockId", value);
    }

    public Boolean getSelectedBlock() {
        return (Boolean)getAttribute("SelectedBlock");
    }

    public void setSelectedBlock(Boolean value) {
        setAttribute("SelectedBlock", value);
    }
}
