package model.bulkeditgroups.services;

import model.bulkeditgroups.views.BlockGroupsUpdtVOImpl;
import model.bulkeditgroups.views.BlocksRoVOImpl;
import model.bulkeditgroups.views.GroupHeaderUpdtVOImpl;
import model.bulkeditgroups.views.MeterOpScheduleRoVOImpl;
import model.bulkeditgroups.views.MeterRateScheduleRoVOImpl;
import model.bulkeditgroups.views.ParkingSpaceGroupsUpdtVOImpl;
import model.bulkeditgroups.views.ParkingSpaceInventoryRoVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 10:09:29 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupsAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GroupsAMImpl() {
    }

    /**
     * Container's getter for BlocksRoVO1.
     * @return BlocksRoVO1
     */
    public BlocksRoVOImpl getBlocksRoVO1() {
        return (BlocksRoVOImpl)findViewObject("BlocksRoVO1");
    }

    /**
     * Container's getter for ParkingSpaceInventoryRoVO1.
     * @return ParkingSpaceInventoryRoVO1
     */
    public ParkingSpaceInventoryRoVOImpl getParkingSpaceInventoryRoVO1() {
        return (ParkingSpaceInventoryRoVOImpl)findViewObject("ParkingSpaceInventoryRoVO1");
    }

    /**
     * Container's getter for GroupHeaderUpdtVO1.
     * @return GroupHeaderUpdtVO1
     */
    public GroupHeaderUpdtVOImpl getGroupHeaderUpdtVO1() {
        return (GroupHeaderUpdtVOImpl)findViewObject("GroupHeaderUpdtVO1");
    }

    /**
     * Container's getter for BlockGroupsUpdtVO1.
     * @return BlockGroupsUpdtVO1
     */
    public BlockGroupsUpdtVOImpl getBlockGroupsUpdtVO1() {
        return (BlockGroupsUpdtVOImpl)findViewObject("BlockGroupsUpdtVO1");
    }

    /**
     * Container's getter for ParkingSpaceGroupsUpdtVO1.
     * @return ParkingSpaceGroupsUpdtVO1
     */
    public ParkingSpaceGroupsUpdtVOImpl getParkingSpaceGroupsUpdtVO1() {
        return (ParkingSpaceGroupsUpdtVOImpl)findViewObject("ParkingSpaceGroupsUpdtVO1");
    }

    /**
     * Container's getter for BlocksUpdtVO1.
     * @return BlocksUpdtVO1
     */
    public ViewObjectImpl getBlocksUpdtVO1() {
        return (ViewObjectImpl)findViewObject("BlocksUpdtVO1");
    }

    /**
     * Container's getter for BlockGroupsUpdtVO2.
     * @return BlockGroupsUpdtVO2
     */
    public BlockGroupsUpdtVOImpl getBlockGroupsUpdtVO2() {
        return (BlockGroupsUpdtVOImpl)findViewObject("BlockGroupsUpdtVO2");
    }

    /**
     * Container's getter for BlocksUpdtVO2.
     * @return BlocksUpdtVO2
     */
    public ViewObjectImpl getBlocksUpdtVO2() {
        return (ViewObjectImpl)findViewObject("BlocksUpdtVO2");
    }

    /**
     * Container's getter for ParkingSpaceInventoryUpdtVO1.
     * @return ParkingSpaceInventoryUpdtVO1
     */
    public ViewObjectImpl getParkingSpaceInventoryUpdtVO1() {
        return (ViewObjectImpl)findViewObject("ParkingSpaceInventoryUpdtVO1");
    }

    /**
     * Container's getter for ParkingSpaceGroupsUpdtVO2.
     * @return ParkingSpaceGroupsUpdtVO2
     */
    public ParkingSpaceGroupsUpdtVOImpl getParkingSpaceGroupsUpdtVO2() {
        return (ParkingSpaceGroupsUpdtVOImpl)findViewObject("ParkingSpaceGroupsUpdtVO2");
    }

    /**
     * Container's getter for ParkingSpaceInventoryUpdtVO2.
     * @return ParkingSpaceInventoryUpdtVO2
     */
    public ViewObjectImpl getParkingSpaceInventoryUpdtVO2() {
        return (ViewObjectImpl)findViewObject("ParkingSpaceInventoryUpdtVO2");
    }

    /**
     * Container's getter for GroupHeaderBlockGroupsVL1.
     * @return GroupHeaderBlockGroupsVL1
     */
    public ViewLinkImpl getGroupHeaderBlockGroupsVL1() {
        return (ViewLinkImpl)findViewLink("GroupHeaderBlockGroupsVL1");
    }

    /**
     * Container's getter for GroupHeaderParkingSpaceGroupsVL1.
     * @return GroupHeaderParkingSpaceGroupsVL1
     */
    public ViewLinkImpl getGroupHeaderParkingSpaceGroupsVL1() {
        return (ViewLinkImpl)findViewLink("GroupHeaderParkingSpaceGroupsVL1");
    }

    /**
     * Container's getter for BlockGroupsBlocksVL.
     * @return BlockGroupsBlocksVL
     */
    public ViewLinkImpl getBlockGroupsBlocksVL() {
        return (ViewLinkImpl)findViewLink("BlockGroupsBlocksVL");
    }

    /**
     * Container's getter for ParkingSpaceGroupsParkingSpaceVL.
     * @return ParkingSpaceGroupsParkingSpaceVL
     */
    public ViewLinkImpl getParkingSpaceGroupsParkingSpaceVL() {
        return (ViewLinkImpl)findViewLink("ParkingSpaceGroupsParkingSpaceVL");
    }

    /**
     * Container's getter for MeterRateScheduleRoVO1.
     * @return MeterRateScheduleRoVO1
     */
    public ViewObjectImpl getMeterRateScheduleRoVO1() {
        return (ViewObjectImpl)findViewObject("MeterRateScheduleRoVO1");
    }

    /**
     * Container's getter for MeterOpScheduleRoVO1.
     * @return MeterOpScheduleRoVO1
     */
    public ViewObjectImpl getMeterOpScheduleRoVO1() {
        return (ViewObjectImpl)findViewObject("MeterOpScheduleRoVO1");
    }

    /**
     * Container's getter for GroupHeaderLastUpdUserLovVO1.
     * @return GroupHeaderLastUpdUserLovVO1
     */
    public ViewObjectImpl getGroupHeaderLastUpdUserLovVO1() {
        return (ViewObjectImpl)findViewObject("GroupHeaderLastUpdUserLovVO1");
    }

    /**
     * Container's getter for GroupHeaderGroupTypeLovVO1.
     * @return GroupHeaderGroupTypeLovVO1
     */
    public ViewObjectImpl getGroupHeaderGroupTypeLovVO1() {
        return (ViewObjectImpl)findViewObject("GroupHeaderGroupTypeLovVO1");
    }
}
