package model.availableapioverrides.views;

import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:49:27 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailApiBlockfacesVwRoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BlockfaceId {
            public Object get(AvailApiBlockfacesVwRoVORowImpl obj) {
                return obj.getBlockfaceId();
            }

            public void put(AvailApiBlockfacesVwRoVORowImpl obj, Object value) {
                obj.setBlockfaceId((Number)value);
            }
        }
        ,
        Description {
            public Object get(AvailApiBlockfacesVwRoVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(AvailApiBlockfacesVwRoVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        RowID {
            public Object get(AvailApiBlockfacesVwRoVORowImpl obj) {
                return obj.getRowID();
            }

            public void put(AvailApiBlockfacesVwRoVORowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        SelectedBlockface {
            public Object get(AvailApiBlockfacesVwRoVORowImpl obj) {
                return obj.getSelectedBlockface();
            }

            public void put(AvailApiBlockfacesVwRoVORowImpl obj, Object value) {
                obj.setSelectedBlockface((Boolean)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(AvailApiBlockfacesVwRoVORowImpl object);

        public abstract void put(AvailApiBlockfacesVwRoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BLOCKFACEID = AttributesEnum.BlockfaceId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int SELECTEDBLOCKFACE = AttributesEnum.SelectedBlockface.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AvailApiBlockfacesVwRoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BlockfaceId.
     * @return the BlockfaceId
     */
    public Number getBlockfaceId() {
        return (Number) getAttributeInternal(BLOCKFACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockfaceId.
     * @param value value to set the  BlockfaceId
     */
    public void setBlockfaceId(Number value) {
        setAttributeInternal(BLOCKFACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowID.
     * @return the RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowID.
     * @param value value to set the  RowID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedBlockface.
     * @return the SelectedBlockface
     */
    public Boolean getSelectedBlockface() {
        return (Boolean) getAttributeInternal(SELECTEDBLOCKFACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedBlockface.
     * @param value value to set the  SelectedBlockface
     */
    public void setSelectedBlockface(Boolean value) {
        setAttributeInternal(SELECTEDBLOCKFACE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
