package model.availableapioverrides.views;

import model.availableapioverrides.views.common.AvailApiBlocksVwRoVORow;

import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:42:56 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailApiBlocksVwRoVORowImpl extends ViewRowImpl implements AvailApiBlocksVwRoVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BlockId {
            public Object get(AvailApiBlocksVwRoVORowImpl obj) {
                return obj.getBlockId();
            }

            public void put(AvailApiBlocksVwRoVORowImpl obj, Object value) {
                obj.setBlockId((Number)value);
            }
        }
        ,
        Description {
            public Object get(AvailApiBlocksVwRoVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(AvailApiBlocksVwRoVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        RowID {
            public Object get(AvailApiBlocksVwRoVORowImpl obj) {
                return obj.getRowID();
            }

            public void put(AvailApiBlocksVwRoVORowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        SelectedBlock {
            public Object get(AvailApiBlocksVwRoVORowImpl obj) {
                return obj.getSelectedBlock();
            }

            public void put(AvailApiBlocksVwRoVORowImpl obj, Object value) {
                obj.setSelectedBlock((Boolean)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(AvailApiBlocksVwRoVORowImpl object);

        public abstract void put(AvailApiBlocksVwRoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int BLOCKID = AttributesEnum.BlockId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int SELECTEDBLOCK = AttributesEnum.SelectedBlock.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AvailApiBlocksVwRoVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BlockId.
     * @return the BlockId
     */
    public Number getBlockId() {
        return (Number) getAttributeInternal(BLOCKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BlockId.
     * @param value value to set the  BlockId
     */
    public void setBlockId(Number value) {
        setAttributeInternal(BLOCKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowID.
     * @return the RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowID.
     * @param value value to set the  RowID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedBlock.
     * @return the SelectedBlock
     */
    public Boolean getSelectedBlock() {
        return (Boolean) getAttributeInternal(SELECTEDBLOCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedBlock.
     * @param value value to set the  SelectedBlock
     */
    public void setSelectedBlock(Boolean value) {
        setAttributeInternal(SELECTEDBLOCK, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
