package model.availableapioverrides.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 21:49:27 PST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AvailApiBlockfacesVwRoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AvailApiBlockfacesVwRoVOImpl() {
    }
}
